feat(be): Implement Authentication/Authorization process with JWT Token
skkuding/next pull request #105
Opened 2022-07-04 19:12 UTC by cranemont

### Description

- JWT Token 기반의 Authentication/Authorization을 구현합니다. 대부분의 로직은 #49 의 Use Case와 동일하지만 `Access Token`을 FE에서 변수에 저장하게 되면 새로고침 시 `reissue API`에 넘겨줄 방법이 없어 `Refresh Token`만을 사용하여 토큰을 재발행하도록 하였습니다. 추가적인 보안을 고려한다면 [IP 정보를 추가하여 검증](https://pomo0703.tistory.com/208)하는 방법이 있습니다.
- Logout시 보안을 위해 [BlackList를 사용하는 방법](https://dev.to/chukwutosin_/how-to-invalidate-a-jwt-using-a-blacklist-28dl)도 있으나, 매번 DB를 확인해야 하는 session방식의 단점을 그대로 가져가고, 너무 stateful한 방식이 되는 것 같아서 제외하였습니다. 대신 `Access Token`의 만료 기간을 짧게 설정하였습니다.
- 암호화 알고리즘으로는 단일키 방식인 HS256을 사용합니다. 보안을 위해서 production 환경에서는 RS256으로 변경될 수 있습니다.
- 아직 exception이나 validation 패턴이 정해진 것이 없어 임의로 구현했습니다. Service layer에서 발생하는 Business logic 관련 exception들은 status code에 관여하지 않고, controller에서 user-friendly하게 변경하도록 구현했습니다. 정상적인 response와 exception 발생시의 response의 형태를 일관되게 하기 위해 global [exception filter](https://docs.nestjs.com/exception-filters#exception-filters-1)를 고려해 볼 수 있습니다. 더 자세한 논의는 #99 에서 진행하겠습니다.

Closes #49 

### Additional context

FE 관점에서 정리한 로직입니다
1. 로그인
`/auth/login`
username과 password 검증
access token과 refresh token을 새로 발급해서
access token을 authorization header에,
refresh token을 httponly secure cookie에 저장 후 response
cache에 refresh token을 같이 저장

2. 로그인이 필요한 요청을 보낼 때
access token을 `authorization header`에 포함하여 request
`JwtGuard`에서 token verification 후 payload의 userId로 User를 찾음
req.user에 `AuthenticatedUser`를 저장
추후 `RoleGuard` 구현에 사용 가능

3. Access Token expiration 시간이 얼마 남지 않았거나 만료되었을 때
`/auth/reissue`
cookie의 refresh token 검증
access token과 refresh token을 새로 발급해서
access token을 authorization header에,
refresh token을 httponly secure cookie에 저장 후 response
cache에 refresh token을 같이 저장

4. 인증이 필요한 페이지를 새로고침 했을 때
page mount할때 `/auth/reissue` 호출

5. 로그아웃 요청 시
`/auth/logout`
`JwtGuard`로 Access Token 검증
Cache에 있는 해당 user의 refresh token 삭제
refresh token cookie 만료시키는 헤더 response
성공시 FE에서 새로고침

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-07-04 19:13 UTC, cranemont commented
Test code는 아직 작성중이지만 시간이 너무 지체되는 것 같아 PR 올립니다. 작성하는 대로 commit 남기겠습니다!

2022-07-06 08:45 UTC, Anzanda requested changes

2022-07-06 13:13 UTC, cranemont commented on backend/src/auth/auth.controller.ts
> +      throw new InternalServerErrorException('Login failed')
#99 에 comment에 이어서 설명하자면, business logic 관련 exception이 던져졌을 때 controller에서는 그에 맞는 적절한 HTTP status code를 정해서 `HttpException`을 던지는 구조입니다. 그러면 service layer에서 어떤 exception이 던져졌나를 확인해야 하는데 다른 방법이 있을까요?

2022-07-06 13:19 UTC, cranemont commented on backend/src/auth/strategy/jwt.strategy.ts
> +    }
쓰고나니까 매번 Guard를 통과할 때마다 DB를 검사해야 하네요. JWT 의도에 맞지 않게 너무 stateful하게 만들어버린 것 같아요 🤔🤔 해당 역할은 RolesGuard를 만들어서 거기로 넘기겠습니다. Issue로 등록하고 따로 구현할게요

2022-07-06 14:19 UTC, Anzanda commented on backend/src/auth/auth.controller.ts
> +      throw new InternalServerErrorException('Login failed')
`instanceof`땜에 적은건데 아닙니다 넘어가요

2022-07-08 02:06 UTC, minseo999 requested changes

2022-07-08 02:06 UTC, minseo999 commented on backend/src/auth/auth.service.ts
> +    if (!user || !(await validate(loginUserDto.password, user.password))) {
validate()함수 첫번째 인자가 hash string이고 두번째 인자가 plain string이어서 2개 순서가 바뀌어야 합니다
`validate(user.password, loginUserDto.password)`

2022-07-08 05:27 UTC, cranemont commented on backend/src/auth/auth.service.ts
> +    if (!user || !(await validate(loginUserDto.password, user.password))) {
수정했습니다~~

2022-07-08 07:38 UTC, cranemont commented on backend/src/auth/auth.controller.ts
> +    @Req() req: AuthenticatedRequest,
DTO는 계층간 데이터 이동이 필요할때 특정 property를 가지는 object를 만들기 위해 사용하고, interface는 특정 property를 가지는 object 형식을 지정하기 위해 사용합니다. DTO와 interface의 구분이라기보다는 class와 interface의 구분이라고 생각했는데, TypeScript의 interface는 JS로 트랜스파일 했을 때 없어지기 때문에 runtime에서 아무런 역할도 하지 않아요. class를 사용한다면 코드에 정의해둔 class의 instance임을 runtime에서 활용할 수 있게 됩니다. 그래서 보통 DTO를 class로 사용하고, instance를 만들어서 계층간에 데이터를 교환합니다.
`logout API`에서 interface를 사용해서 `req`의 type을 `AuthenticatedRequest`으로 지정한 이유는, 그래야 `req.user` 처럼 사용할 수 있기 때문입니다. JwtAuthGuard를 통과하면서 `req.user`에 `AuthenticatedUser` 형식의 object 가 저장되는데, `req`는 express의 `Request` 객체이기 때문에 그냥 `req.user.id`처럼 접근한다면 compile시 에러가 발생하게 돼요. 그래서 Express의 Request를 extend하는 `AuthenticatedRequest` interface를 만들고, 해당 interface에 `AuthenticatedUser` 형식의 `user` property를 추가하여 사용했습니다. interface와 dto의 구분이라기보다는 타입스크립트 문법이라고 보시면 될 것 같아요.
결론을 말씀드리자면 interface는 data type을 지정할 때, DTO는 validation같이 runtime에서 class를 활용해야 할 때 사용한다고 생각합니당

2022-07-11 07:55 UTC, cranemont commented
일단 service의 unit test만 추가하였습니다. 내일까지 any-question 채널에서 controller unit test 여부에 대해 얘기해보고 추가하거나 merge할게요!

2022-07-12 08:02 UTC, minseo999 approved these changes

2022-07-12 08:07 UTC, Anzanda approved these changes

2022-07-12 08:17 UTC, minseo999 requested changes

2022-07-12 08:27 UTC, minseo999 commented on backend/prisma/schema.prisma
> +  role                    String   @default("user")
테스트코드도 수정해주세요~!

2022-07-12 08:33 UTC, merged