feat(fe): add footer component
skkuding/next pull request #106
Opened 2022-07-06 02:44 UTC by djc06048

### Description

Footer 구현

깃헙, 카카오톡, 링크 아이콘 클릭시 해당 url로 이동하도록 하였습니다.
메시지 아이콘의 경우 누르는 동작은 해당되는 피그마가 없어, 콘솔에 해당 동작이 뜨게끔만 구현했습니다.

close #81

2022-07-06 05:00 UTC, SOLBI1028 commented
v-clipboard가 정상적으로 동작하지 않아서 수정해서 커밋 올렸고, description에 언급된 바와 같이 모달 컴포넌트가 아직 만들어지지 않아서 copy후에 alert 창이 뜨도록 설정해두었습니다!

2022-07-06 06:13 UTC, dotoleeoak requested changes

2022-07-06 06:13 UTC, dotoleeoak commented on frontend/src/common/components/Organism/Footer.vue
> +import PhLinkThin from '~icons/ph/link-thin'
4개가 icon set을 서로 다른 걸 쓰고 있는데, 되도록 일관된 icon set을 쓰는 게 미관상 좋아보일 것 같아요.
코딩플랫폼이 전반적으로 둥글고 부드러운 느낌이라 font awesome이 좋아보이고(그 중에도 solid), 카카오톡 아이콘은 font awesome에 없으니까 다른 set에 적당한 걸로 대체하면 될 것 같습니다. 🙂

### Before

![image](https://user-images.githubusercontent.com/19747913/177479347-f3c26cf2-2b8d-41bc-88b5-7259d5fd7f03.png)

### After

![image](https://user-images.githubusercontent.com/19747913/177480955-da76eadb-b004-4dda-b096-1d0583f25425.png)

2022-07-06 13:24 UTC, goo314 commented on frontend/src/common/components/Organism/Footer.vue
> +      <span>© 2011-2022 SKKUDING</span>
이거 2020-2022 으로 바꿔주세요 너무 오래 됐어요 🦖

2022-07-08 13:28 UTC, SOLBI1028 commented on frontend/package.json
> +    "vue3-clipboard": "^1.0.0"
오 vueuse는 처음 알았네요..! 여기서 useClipboard쓰고 앞으로도 활용하면 좋을 것 같습니다 :)

2022-07-11 07:04 UTC, djc06048 commented on frontend/src/common/components/Organism/Footer.vue
> +      console.log(error)
넵!

2022-07-11 07:05 UTC, djc06048 commented on frontend/src/common/components/Organism/Footer.vue
> +import PhLinkThin from '~icons/ph/link-thin'
넵 변경해서 다시 올리겠습니다~!

2022-07-14 08:24 UTC, dotoleeoak commented
footer 디자인 일부 수정했습니다
불필요한 `div` tag 없앴고, transition 등 몇몇 class 추가했으니 확인해주세요~!

![CPT2207141636-324x126](https://user-images.githubusercontent.com/19747913/178936998-a5b43380-39d3-4c74-86f1-7fe1b2052019.gif)

2022-07-14 08:51 UTC, dotoleeoak approved these changes

2022-07-18 12:31 UTC, merged