feat(fe): add switch component
skkuding/next pull request #108
Opened 2022-07-06 09:00 UTC by kee711

### Description

Switch 구현

closes #76

#### 사용법
- 상위 컴포넌트에서 label 지정 필요
- false일때
![image](https://user-images.githubusercontent.com/59683761/177512213-9e0abfaa-c81f-43c2-aaba-27d7d299cb86.png)
- true일때
![image](https://user-images.githubusercontent.com/59683761/177512288-441dd2e5-ab4c-46fb-b645-2e19b267dc12.png)

- 상위 컴포넌트에서 해당 데이터가 true인지 false인지 switchdata로 받을 수 있음

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-07-06 13:15 UTC, goo314 commented on frontend/src/common/components/Molecule/Switch.vue
> +var switchdata = ref(0)
어차피 true, false로만 쓰이니까 `var data = ref(true)` 로 해도 되지 않을까요?

2022-07-06 13:16 UTC, goo314 commented on frontend/src/common/components/Molecule/Switch.vue
> +      class="relative flex h-6 w-12 rounded-full border-2"
개인적으로 마우스 커서를 스위치에 올리면 바뀌는 `cursor-pointer` tailwindcss도 추가하면 좋을 것 같아요!

2022-07-06 13:22 UTC, goo314 commented on frontend/src/common/components/Molecule/Switch.vue
> +var switchdata = ref(0)
만약 한다면 `@click="switchdata = !switchdata` 이렇게 코드 짜면 간단할 것 같은데 되는지는 모르겠네요😃

2022-07-15 08:06 UTC, dotoleeoak requested changes

2022-07-17 16:09 UTC, kee711 commented on frontend/src/common/components/Molecule/Switch.vue
> +  </div>
```
 <label
    for="default-toggle"
    class="relative inline-flex cursor-pointer items-center"
  >
    <input
      type="checkbox"
      value=""
      id="default-toggle"
      class="peer sr-only"
      @click="switchdata = !switchdata"
    />
    <div
      class="peer-checked:border-green peer-checked:after:bg-green after:bg-gray border-gray peer relative h-6 w-12 rounded-full border-2 bg-white after:absolute after:top-0 after:bottom-0 after:my-auto after:h-3 after:w-3 after:rounded-full after:transition-all after:content-[''] checked:after:translate-x-full peer-checked:after:translate-x-full"
    ></div>
    <span class="ml-3 text-sm font-medium text-gray-900 dark:text-gray-300">
      Toggle me
    </span>
  </label>
```

https://flowbite.com/docs/forms/toggle/ 
위 링크 방식대로 우리 스타일에 맞게 변형해서 만들어봤는데 한 태그 안에 너무 css를 쭉 늘어놓게 되다보니 되려 코드가 너무 지저분해 지더라고요ㅠ 혹시 그럼에도 불구하고 div말고 Input태그를 활용했을때의 특별한 장점이 있어서 input을 활용하라고 말씀해주신걸까요? 만약 그렇다면 태그 안에 css class 길게 덕지덕지 쓰지 않고 해결할 수 있는 방법이 있을까요?

2022-07-19 08:22 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/Switch.vue
> +  </div>
input tag를 안 쓰면 구현은 조금 더 편해지겠지만 semantic HTML을 위해서 적절한 tag를 쓰는 게 좋습니다.
실제 사용자는 HTML 파일을 읽을 일이 없지만, Google 같은 검색엔진과 브라우저는 HTML로 내용을 인식하기 때문에 의미 있는 tag를 사용하는 게 바람직하겠죠?

2022-07-19 08:23 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/Switch.vue
> +  </div>
구현상 CSS를 많이 줄일 수는 없긴 한데, 아래는 제가 짜본 switch component니까 한 번 참고해보세요.

```vue
<script setup lang="ts">
import { ref } from 'vue'

const props = defineProps<{
  label?: string
  modelValue: boolean
}>()

defineEmits<{
  (e: 'update:modelValue', value: boolean): void
}>()

const data = ref(props.modelValue)
</script>

<template>
  <label class="[&>*]:cursor-pointer inline-flex items-center gap-2">
    <input
      v-model="data"
      type="checkbox"
      role="switch"
      class="bg-gray checked:bg-green grid h-6 w-12 appearance-none rounded-full p-1 before:h-4 before:w-4 before:rounded-full before:bg-white before:transition checked:before:translate-x-6"
      @change="$emit('update:modelValue', data)"
    />
    <span v-if="label" class="text-sm">
      {{ label }}
    </span>
  </label>
</template>
```

2022-07-19 08:25 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/Switch.vue
> +  </div>
더 퀄리티 있는 switch component 예시를 보고 싶으시면 Google 개발자인 [Adam Argyle](https://web.dev/authors/adamargyle/)가 직접 쓴 글도 참고해보세요~!
https://web.dev/building-a-switch-component/

2022-07-23 13:55 UTC, SOLBI1028 commented
민성님이 잠시 여행을 가서 제가 다시 구현했습니다! 확인 부탁드립니다! @dotoleeoak

2022-07-26 13:49 UTC, dotoleeoak approved these changes

2022-07-26 13:49 UTC, dotoleeoak commented
`v-model` 쓸 수 있게 코드 일부 수정했습니다~!

2022-07-27 06:19 UTC, merged