feat(be): make password reset logic with nodemailer
skkuding/next pull request #109
Opened 2022-07-06 10:43 UTC by SH9480P

### Description

- 비밀번호를 재설정하는 로직을 구현했습니다.
- 사용자로부터 비밀번호 재설정용 이메일을 받는 부분(sendPwResetEmail), 새로운 비밀번호를 설정하는 부분(updatePassword)으로 나뉩니다.
- 새로운 비밀번호는 argon2로 해쉬화하여 저장합니다.

Closes #50 

### Additional context

**Logic Flow**
(fe) 사용자가 비밀번호를 바꾸기 위해, 본인 이메일로 재설정 링크를 요청합니다
(be) 회원가입된 사용자인지 확인하고, 토큰을 생성하여 이메일로 토큰을 포함하는 재설정 링크를 전송합니다
(fe) 이메일로 전송된 링크로 들어간 뒤, 재설정할 비밀번호를 전송합니다
(be) 사용자 id와 token이 존재하는지 확인한 뒤, 새로 받은 비밀번호를 해쉬화하여 저장합니다.

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-07-08 09:35 UTC, SH9480P commented
PR이 늦었습니다 ㅜㅜ
unit testing을 시도중인데 prisma mock 객체를 만드는게 어렵네요
test suites 완전히 작성되면 commit하겠습니다

2022-07-16 09:27 UTC, cranemont commented
main브랜치의 커밋들 drop 부탁드릴게요! 변경된 부분을 확인하기가 어렵네요😥😥
[여기](https://wormwlrm.github.io/2020/09/03/Git-rebase-with-interactive-option.html) 참고하시거나 잘 안되시면 DM 주세요~~~

2022-07-21 13:27 UTC, SH9480P commented
> main브랜치의 커밋들 drop 부탁드릴게요! 변경된 부분을 확인하기가 어렵네요😥😥 [여기](https://wormwlrm.github.io/2020/09/03/Git-rebase-with-interactive-option.html) 참고하시거나 잘 안되시면 DM 주세요~~~

drop했습니다!

2022-07-22 06:58 UTC, minseo999 commented on backend/src/user/newPw.dto.ts
> +export class NewPwDto {
class명을 NewPasswordDto로 하는게 더 명확할 것 같습니다!

2022-07-22 07:08 UTC, minseo999 requested changes

2022-07-22 07:08 UTC, minseo999 commented on backend/src/common/cache/keys.ts
> +export const pwResetTokenCacheKey = (userId: number) => `pw-reset:${userId}`
변수명이 조금 길어지더라도 `passwordResetTokenCacheKey` 로 설정하면 좋을 것 같은데, 어떨까요?

2022-07-22 11:42 UTC, SH9480P commented
수정했습니다!

2022-08-03 19:10 UTC, SH9480P commented
수정사항 반영해서 commit했습니다~
CodeQL에 Clear text storage of sensitive information warning 뜨는 것은 쿠키에 jwt 그대로 담는게 위험하다고 경고하는거 같아요
production에서는 secure true 옵션 줄 테니 지금은 그냥 넘어가도 괜찮지 않을까 생각합니다

2022-08-05 07:29 UTC, minseo999 commented on backend/src/user/dto/userEmail.dto.ts
> +  email: string
class validator 추가해주세요!
`@IsEmail(), @IsNotEmpty()`

2022-08-05 07:32 UTC, minseo999 commented on backend/src/user/user.service.ts
> +  async createPinAndSendEmail({ email }: UserEmailDto): Promise<string> {
property 하나만 있는 Dto에서 Dto.email 이런식으로 사용하는게 번거로웠는데, parameter를 이런식으로 받아오는 것도 좋네요!

2022-08-05 08:18 UTC, minseo999 commented on backend/src/user/user.service.ts
> +    await this.createPinInCache(passwordResetPinCacheKey(user.email), pin, 300)
ttl은 상수로 정의해두고 사용하는게 좋을 것 같아요

2022-08-05 08:20 UTC, minseo999 commented on backend/src/user/user.service.ts
> +  async verifyPinAndIssueJwtTokenForPasswordReset({
method이름 `verifyPinAndIssueJwtForPasswordReset` 으로 줄여도 될 것 같아요!

2022-08-05 08:23 UTC, minseo999 commented on backend/src/user/user.service.ts
> +    return await this.jwtService.signAsync(payload, { expiresIn: 300 })
마찬가지로 expiresIn 상수로 정의해서 지정해주세요!

2022-08-06 16:30 UTC, minseo999 commented on backend/src/common/exception/business.exception.ts
> +export class EmailTransmissionFailedException extends BusinessException {}
메일 전송 실패 예외는 메세지가 정해져있는 것 같아요! throw 할 때 메세지를 직접 넣어주는 방식 대신 constructor로 메세지를 넣어주는 건 어떨까요?

```
class EmailTransmissionFailedException extends BusinessException{
    constructor(message) {
      super('Email transmission failed')
  }
}
```
이렇게 하고 error 던질 때는 그냥
`throw new EmailTransmissionFailedException()` 이렇게 할 수 있도록이요!

2022-08-06 16:52 UTC, minseo999 commented on backend/src/user/user.controller.ts
> +  async verifyPinAndIssueJwtToken(
마찬가지로 이 메서드랑 `setJwtTokenInCookie()` 메서드 이름도 `verifyPinAndIssueJwt()` `setJwtInCookie()` 로 줄이면 좋을 것 같습니다~!

2022-08-06 17:20 UTC, minseo999 commented on backend/src/user/user.service.ts
> +    }
`line 133`~ `line 139`는 verifyPin() 등 별도 메서드로 분리하는게 좋아보여요
본 메서드가 역할이 2개 이기도 하고 분리하면 다른 기능에서도 활용하기 좋을 것 같습니다~!

2022-08-06 17:29 UTC, minseo999 commented on backend/src/user/user.service.ts
> +    }
`updatePassword()`에 있는 캐시 delete 하는 로직 `await this.deletePinFromCache(passwordResetPinCacheKey(req.user.email))` 이 이부분에 들어가는게 더 적절해보이는데, 어떻게 생각하시나요??

2022-08-06 18:02 UTC, minseo999 requested changes

2022-08-06 18:06 UTC, minseo999 commented on backend/src/user/user.service.spec.ts
> +import { Request } from 'express'
사용하지 않는 import 지워주세요!

2022-08-06 18:06 UTC, minseo999 commented on backend/src/user/interface/getRequestUserProp.interface.ts
> +import { Request } from 'express'
사용하지 않는 import 지워주세요~!

2022-08-08 11:14 UTC, SH9480P commented on backend/src/email/email.service.ts
> +      html: `<div>If you want to reset your password, Put the pin numbers below into the password reset page.</div>
이슈 등록하겠습니다~~

2022-08-08 12:29 UTC, SH9480P commented on backend/src/user/user.service.ts
> +    }
> `updatePassword()`에 있는 캐시 delete 하는 로직 `await this.deletePinFromCache(passwordResetPinCacheKey(req.user.email))` 이 이부분에 들어가는게 더 적절해보이는데, 어떻게 생각하시나요??

이 부분이 line 136~139를 말씀하시는건가요?

2022-08-08 12:38 UTC, SH9480P commented on backend/src/user/interface/getRequestUserProp.interface.ts
> +  }
위에 comment 남겨주셨듯이 cache에서 pin을 삭제하는 시점을 jwt 발급 직전으로 변경한다면 email이 필요가 없어지네요.
updatePassword에서 userId로 비밀번호를 변경하게 구현되어있어서 email을 지우고 id를 남기겠습니다!

2022-08-08 13:27 UTC, SH9480P commented on backend/src/user/user.controller.ts
> +  @UseGuards(AuthGuard('passwordReset'))
`@UseGuards(AuthGuard('passwordReset'))`의 사용처가 한정적이라 service단에서 `jwtService.verifyAsync()` 메서드 사용하는 것도 괜찮을 것 같은데.. 위 방식을 제안하신 다른 이유가 있나요?

2022-08-09 15:25 UTC, SH9480P commented
수정했습니다~

2022-08-11 09:30 UTC, cranemont commented on backend/src/user/user.controller.ts
> +      return this.userService.createPinAndSendEmail(userEmailDto)
async await 처리해주세요!

2022-08-11 09:31 UTC, cranemont commented on backend/src/user/user.controller.ts
> +      return this.userService.updatePassword(newPasswordDto, req)
여기도 async await 처리해주세요~!

2022-08-18 15:43 UTC, minseo999 approved these changes

2022-08-19 02:18 UTC, merged