feat(fe): add card component
skkuding/next pull request #115
Opened 2022-07-08 14:02 UTC by djc06048

### Description

Card구현

closes #83

2022-07-09 07:54 UTC, goo314 commented on frontend/src/common/components/Molecule/Card.vue
> +              <span class="ml-2">Notice</span>
Home에서 쓰이는 카드가 Notice만 있는게 아니라서 카드 제목도 props로 받거나 아니면 카드 제목을 `<slot />`으로 비워놓고 아이콘이랑 제목이랑 같이 받으면 좋을 것 같다고 생각하는데 어떻게 생각하시나욤? 🤩

<img width="558" alt="image" src="https://user-images.githubusercontent.com/62930375/178096970-4f1ce2fe-ab54-43d1-a5f2-46845884d6d3.png">

2022-07-12 01:05 UTC, SOLBI1028 commented
이 카드 형식은 home에서 사용되기 때문에 common/components 디렉토리보단 home/components 디렉토리에 있는게 더 맞을 것 같아요!

2022-07-12 01:07 UTC, SOLBI1028 commented
> 이 카드 형식은 home에서 사용되기 때문에 common/components 디렉토리보단 home/components 디렉토리에 있는게 더 맞을 것 같아요!

비슷한 카드 형식이 group admin에도 사용되고 있지만, 내용 형식(home에서는 title-date로 이루어진 table 형식, group admin에서는 description, members를 표시하는 줄글 형식) 이 다르기때문에 다른 카드 형식으로 보는게 맞을 것 같아요!

2022-07-12 01:15 UTC, SOLBI1028 requested changes

2022-07-12 01:15 UTC, SOLBI1028 commented on frontend/src/common/components/Molecule/Card.vue
> +                <a href="#">{{ item.date }}</a>
항목마다 `a` tag를 설정해서 링크로 이동하는 것보다는 table row (`tr` tag)에 클릭이벤트를 설정하고 row를 클릭했을 때 각 notice detail이나 contest detail로 이동하게 하면 어떨까요??

2022-07-15 14:58 UTC, dotoleeoak commented
@djc06048 커밋하면서 component 파일이 사라져버렸어요... 확인 부탁드릴게요

2022-07-18 12:46 UTC, djc06048 commented
> @djc06048 커밋하면서 component 파일이 사라져버렸어요... 확인 부탁드릴게요

수정완료했습니다 확인부탁드려요!

2022-07-20 05:22 UTC, dotoleeoak commented
main 브랜치 merge 해뒀고, `common` 모듈에 남아있던 파일은 필요없는 거 같아서 지웠습니다~~!

2022-07-20 05:37 UTC, dotoleeoak requested changes

2022-07-20 05:37 UTC, dotoleeoak commented on frontend/src/home/components/Card.vue
> +import MaterialSymbolsArrowForwardIosRounded from '~icons/material-symbols/arrow-forward-ios-rounded'
https://github.com/skkuding/next/pull/106#discussion_r914449228 에서 언급한 것처럼 icon set을 하나로 통일하는 게 좋을 것 같아요. 이 부분도 font awesome으로 바꾸는 거 어떨까요?

2022-07-20 05:37 UTC, dotoleeoak commented on frontend/src/home/components/Card.vue
> +  </div>
이렇게 구현해도 큰 문제는 없긴 한데, 다른 방식으로 구현하면 element가 적어져서 코드가 좀 더 단순해질 거 같아요.

```html
<div>
  <div><!-- 제목, 메뉴 아이콘 --></div>
  <ul>
    <li><!-- 링크 1 --></li>
    <li><!-- 링크 2 --></li>
    <li><!-- 링크 3 --></li>
  </ul>
</div>
```

![image](https://user-images.githubusercontent.com/19747913/179904637-d4c3348d-41a3-42fc-b4a4-4b3d6b99bb87.png)

2022-07-20 14:04 UTC, djc06048 commented on frontend/src/home/components/Card.vue
> +  </div>
테이블을 사용한 이유가 정렬이 되게끔인데, td 태그를 이용안하고 말씀하신 것처럼 li태그를 활용하면 정렬을 클래스에서 다시 지정해줘야하지 않나요?

2022-07-22 14:32 UTC, dotoleeoak commented on frontend/src/home/components/Card.vue
> +  </div>
아마 flex로 정렬을 해줘야되긴 할텐데, 지금도 정렬은 flex로 해주고 있으니까 class는 큰 차이 없을 것 같아요

2022-07-22 14:42 UTC, djc06048 commented on frontend/src/home/components/Card.vue
> +  </div>
table태그 대신에 li 태그로 바꾸라는 말씀이신가요?!

2022-07-23 07:52 UTC, SOLBI1028 requested changes

2022-07-23 07:52 UTC, SOLBI1028 commented on frontend/src/home/components/Card.vue
> +  noticelist: data[]
카드가 notice, contest에서 사용되니까 props이름도 noticelist 보다는 items 같이 두 리스트를 모두 포괄할 수 있도록 사용하면 좋을 것 같아요!

2022-07-23 07:52 UTC, SOLBI1028 commented on frontend/src/home/components/Card.vue
> +                ></slot>
아이콘에 slot을 3개를 두는것보단 `<slot name="icon">` 처럼 하나의 slot으로만 작성하고, 컴포넌트를 사용할때 지정해주면 좋을 것 같아요
- Notice 일 때
```
<Card>
~~
  <template name="icon"> notice일 때 사용할 아이콘 </template>
~~
```
- Contest 일때 
```
<Card>
  <template name="icon">
    <MdiDotsHorizontal v-if="진행중인 상태" />
    <Fa6RegularCalendar v-else />
  </template>
~~
```

2022-07-23 07:52 UTC, SOLBI1028 commented on frontend/src/home/components/Card.vue
> +          </tr>
이부분이 title 부분인 것 같은데 이부분은 테이블(리스트) 목록에서 빼도 될것 같아요.
이 부분 먼저 리스트랑 분리하고, 리스트를 table -> `<li>`로 정리하면 재민님이 남겨주신 커멘트대로 더 쉽게 리팩토링 할 수 있을 것 같아요!

2022-07-26 00:58 UTC, SOLBI1028 approved these changes

2022-07-26 23:27 UTC, dotoleeoak approved these changes
스타일 일부 변경해뒀습니다~!

![image](https://user-images.githubusercontent.com/19747913/181129069-7004b4cd-565e-40ce-b99d-13ac6fdfd99e.png)

2022-07-27 06:19 UTC, merged