feat(fe): add badge component
skkuding/next pull request #121
Opened 2022-07-14 04:24 UTC by kee711

### Description

Badge 구현

closes #120

#### 사용법

- 상위 컴포넌트에서 props로 endtime(string)과 ended(boolean) 지정 필요
- ended가 true일때 endtime을 표시해주고 false일때 “Ended”문구를 표시해준다.

- `ended: true`

![image](https://user-images.githubusercontent.com/59683761/178897709-6388b72d-a744-47dc-98a0-f70130999d05.png)

- `ended: false`

![image](https://user-images.githubusercontent.com/59683761/178897783-8e810b7c-ec05-4f32-88e8-02de519ee295.png)

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-07-14 04:54 UTC, SOLBI1028 requested changes

2022-07-14 04:54 UTC, SOLBI1028 commented on frontend/src/common/components/Molecule/Badge.vue
> +    ></div>
v-if / v-else로 경우를 나누는것보단 computed 이용해서 객체로 스타일 적용하는게 더 좋을 것 같아요~!

2022-07-14 04:54 UTC, SOLBI1028 commented on frontend/src/common/components/Molecule/Badge.vue
> +}>()
그리고 contest에서만 사용되는게 아니라 problem detail에서 채점 결과를 표시하는데에도 사용되어서, props를 endtime/ended로 나누는것보단 color (원 색깔), text로 나누는게 여러 페이지에서 사용하기 좋을 것 같은데 어떨까요?

2022-07-15 13:53 UTC, dotoleeoak commented
Tailwind CSS에서 dynamic string을 인식하지 못하는 문제 때문에 mapper 코드 추가해뒀습니다~!
review comment로 적기 좀 까다로울 것 같아서 일단 직접 커밋해뒀어요

2022-07-15 14:23 UTC, dotoleeoak requested changes

2022-07-15 14:23 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/Badge.vue
> +  text: string
text는 이 component에서 가장 잘 보이고 자주 변경되는 content니까 props 대신 slot으로 받는 거 어떤가요?
`<Badge text="123456" />` 대신에 `<Badge>123456</Badge>` 처럼 쓸 수 있게요!

2022-07-15 14:23 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/Badge.vue
> +])
text 글자 수에 맞춰서 component 스타일을 결정하는 건 edge case가 생길 것 같아서 조금 고민이네요...
글씨 크기 같은 건 parent에서 class를 직접 적용하는 방향은 어떨까요?
margin은 아래 comment에서 따로 얘기할게요.

2022-07-15 14:23 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/Badge.vue
> +  </div>
스타일을 이런 접근으로 짜보는 건 어떨까요?
badge(파란색 원)와 text의 위치를 각각 생각해보면, badge는 항상 지정된 위치에 고정시키고 text는 오른쪽 공간에서 가운데 정렬이 되게끔 배치하는 거죠.

이렇게 하려면
1. 일단 사각형 안의 좌우에 padding을 주고,
2. badge의 공간과 text의 공간을 할당하고(span을 써도 되고, flexbox를 써도 좋습니다)
3. 각 공간 안에서 위 설명대로 badge는 고정된 크기, text는 남는 오른쪽 공간에서 가운데 정렬하는거죠. 

![image](https://user-images.githubusercontent.com/19747913/179242200-00962d1e-b8fd-4116-ac5c-ec287b47a0b9.png)

2022-07-15 14:23 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/Badge.vue
> +  </div>
글로 설명하려니 전달이 잘 안될 수 있을 것 같은데, 질문 있거나 이해 안되면 댓글 남겨주세요~!

2022-07-21 00:17 UTC, dotoleeoak approved these changes

2022-07-23 09:08 UTC, SOLBI1028 approved these changes

2022-07-23 09:08 UTC, merged