feat(fe): add tab component
skkuding/next pull request #122
Opened 2022-07-14 05:52 UTC by SOLBI1028

### Description
tab component 구현
<img width="952" alt="image" src="https://user-images.githubusercontent.com/75013515/178903983-47e87b54-37a1-4a92-a501-b858868b4148.png">

#### 사용법
1. tab 항목들을 items라는 props로 Tab component로 전달합니다.
2. tab의 색상을 커스텀하는 경우에는 color props로 전달합니다. 
   (group detail page에서는 해당 그룹에 해당하는 색깔에 맞춰 tab을 custom할 수 있습니다)
3. page에서 각 item에 해당하는 컴포넌트를 template으로 작성해주면 됩니다.
```
<Tab :items="items">
    <template #notice>
        notice
        <detail /> // notice 버튼을 누르면 detail component가 tab 밑에 표시됩니다.
    </template>
      <template #contest>
        contest
        <contest />
      </template>
</Tab>
```

### Additional context
tab component의 경우에는 사용자가 색상을 선택하여 적용해야 하기 때문에 동적으로 스타일을 적용할 수 있어야 합니다. 하지만 tailwind css에서는 동적으로 스타일을 적용할 수 없기 때문에 inline style으로 적용하였습니다. 
이 컴포넌트의 경우에는 사용자가 선택할 수 있는 모든 색상에 대해 config파일에 지정해둘 수 없기 때문에 safelist에 해당 스타일을 작성해두거나, 객체로 스타일을 적용하는 경우는 불가능하였습니다.

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-07-14 11:17 UTC, SOLBI1028 commented
> tab component는 header에서만 쓰이지 않나요? header에서만 쓰이면 재사용성을 고려할 필요는 없으니까 `home` module로 옮기거나, 아니면 아예 header component 안으로 코드를 옮기는 거 어떨까요?

이 tab component는 header가 아니라 contest, group 페이지에서 sidebar 역할을 하는 컴포넌트 입니다!
<img width="493" alt="image" src="https://user-images.githubusercontent.com/75013515/178970781-ff4e50dc-4cb9-419a-8844-d14a85d7dbe0.png">

2022-07-15 14:25 UTC, dotoleeoak commented
@SOLBI1028 음... 제가 착각했네요 😅
common에 두는 게 좋을 것 같습니다

2022-07-15 14:52 UTC, dotoleeoak requested changes
구현하기 까다로운 component 같은데, slot이랑 v-for가 잘 활용돼서 구현이 잘 된 것 같네요 👍
스타일 관련된 코드에 댓글 남긴 것만 확인 조금 더 부탁드려요~

2022-07-15 14:52 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/Tab.vue
> +  </div>
Vue 3부터는 multiple root node를 지원해서 `div`로 component 전체를 감싸지 않아도 돼요
그래서 34, 52번째 줄에 있는 div는 없애고, 36번째 줄의 `ul` element에 top/bottom border을 추가하는 거 어떤가요?
그러면 35, 49번째 줄의 `div`도 필요없어서 좀 더 깔끔해질 거 같아요

2022-07-15 14:52 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/Tab.vue
> +}
inline style로 색깔 자유롭게 넣을 수 있게 한 건 좋은 생각인데, hover 같은 기능들 추가하면서 코드가 생각보다 조금 길어진 것 같아요 🤔
대신에 style tag를 추가해서 `v-bind()`로 짜보는 거 어떨까요? 이 방향은 구현이 좀 쉬워질 것 같아요.

Vue 3 v-bind() in CSS: https://vuejs.org/api/sfc-css-features.html#v-bind-in-css

2022-07-18 06:48 UTC, SOLBI1028 commented on frontend/src/common/components/Molecule/Tab.vue
> +  </div>
수정했습니다!

2022-07-18 06:51 UTC, SOLBI1028 commented on frontend/src/common/components/Molecule/Tab.vue
> +}
오 사용자가 커스텀을 할 수 있게 한다면 코드를 이렇게 짜는게 더 좋을 것 같네요!
그런데 progress card에서 달았던 [커멘트 내용](https://github.com/skkuding/next/pull/123#issuecomment-1186811083)처럼 사용자가 color set 중에 선택하게 한다면, 구현 방식이 달라질 것 같아서 방향이 확실히 정해진 후 progress card와 같이 수정하도록 하겠습니다! :)

2022-07-23 08:26 UTC, SOLBI1028 commented on frontend/src/common/components/Molecule/Tab.vue
> +}
@dotoleeoak  혹시 이 컴포넌트도 merge하고 색상 set 설정 후 고쳐도 괜찮을까요~?

2022-07-26 23:41 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/Tab.vue
> +}
네 알겠습니다~

2022-07-26 23:42 UTC, dotoleeoak approved these changes

2022-07-27 06:20 UTC, merged