72 pagination table
skkuding/next pull request #129
Opened 2022-07-15 12:17 UTC by goo314

### Description

- Pagination Table 구현 (close #72 )
- SearchBar 구현 (close #71 )
- Pagination 구현 (close #70 )
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/62930375/179217648-fe1ff1ec-b205-4284-9fa2-08e367fee8ac.png">

### Additional context

- props
자세한 정보는 story.vue에서 확인 바랍니다 😀
  - fields (object[]) 헤더에 들어갈 정보리스트 
    예) `:fields="[{key: 'title'}, {key: 'time', label:'Date'}]"`
  - items (object[]) 각각의 row에 들어갈 정보 리스트 
    예) `:items="[{title: 'SKKUDING, time: 2020-01-01}...]"`
  - placeholder (string) 서치바의 placeholder 
  - numberOfPages (number) 페이지 수
  - text (string) 아이템이 없을때 나타날 글씨
  - noHeader (boolean) 헤더의 유무, true일 경우 헤더 없음
  - noSearchBar (boolean) 서치바의 유무
  - noPagination (boolean) 페이지네이션 버튼의 유무

- event
  - changePage 페이지가 변경 되었을 때
    pagination -> paginationTable -> page
  - search 서치바에서 찾는 정보
    searchBar -> paginationTable -> page
  - rowClicked 해당 열을 눌렀을 경우
    paginationTable -> page

🌟 화면에서 페이지가 나타나는 순서
- (자식 컴포넌트) < (부모 컴포넌트) 라고 할때
- Pagination < PaginationTable < Page 의 경우에서
- 가장 높은 Page에 currentPage 정보가 있습니다.
1. default로 가장 처음에 보여지는 페이지는 1페이지입니다.
2. Pagination 버튼을 눌러 페이지가 변경되면 Page로 변경 이벤트 emit을 보냅니다.
3. Page에 정의된 currentPage가 변경되고 item이 변경됩니다. (api요청으로)
4. 변경된 item정보를 PaginationTable이 prop으로 받아 보여집니다.

### 추가적으로 궁금한 부분
- SearchBar에서 icon의 색깔이 변경되지 않아 기본 css를 썼는데 다른 방법이 있을까요?
- 화면에서 페이지가 나타나는 순서가 저렇게 맞을까요? 
  일단 백엔드에서 한 페이지당 보여줄 아이템 개수가 고정되어있고, 페이지마다 api 요청을 보낸다는 가정하에 시나리오를 작성했습니다.
- 뷰3에서 중간 컴포넌트를 건너뛰고 emit을 보내는 방법 중 `v-bind='$attrs'`(뷰2의 $listeners와 통합되었다고 하네요)를 사용했습니다.
  이 방법은 부모의 css스타일이랑 모든 attribute를 다 받아오기 때문에 PaginationTable 자체에 스타일 속성을 주면 pagination이나 searchbar에 적용되기 때문에 무조건 paginationTable을 쓸때 div로 감싸서 스타일 속성을 주어야 합니다. 괜찮은 방법일까요?
  즉, PaginationTable에 class="mx-40"을 주면 pagination에도 class"mx-40"이 한번 더 적용 됩니다.
  

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-07-17 07:40 UTC, dotoleeoak requested changes

2022-07-17 07:40 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/Pagination.vue
> +</template>
페이지 세 개 보여주는 걸로도 기능은 충분할 수 있긴 한데, 다른 사이트들 예시들을 보면 좀 더 사용자가 쓰기 쉽게 만들 수도 있을 것 같아요. 대충 예시 나열해보면 GitHub 같은 Pagination이 좀 흔하게 쓰이는 것 같고, AtCoder는 독특하게 되어있는데 페이지가 많은 경우에 되게 유용한 것 같아요.

제가 디자인 단계의 구체적인 내용을 몰라서 그럴 수도 있으니 관련 의견 댓글로 남겨주세요...!

#### [GitHub](https://github.com/vitejs/vite/issues)
![image](https://user-images.githubusercontent.com/19747913/179387698-3a135c06-e018-4b12-a16b-65b2557d8f7b.png)

#### [AtCoder](https://atcoder.jp/ranking)
![image](https://user-images.githubusercontent.com/19747913/179387676-ad39cb9f-b76d-44c8-9201-69ddbe4b967a.png)

#### [Amazon](https://www.amazon.com/s?k=macbook&crid=15BDONLALVOR9&sprefix=macbo%2Caps%2C408&ref=nb_sb_noss_2)
![image](https://user-images.githubusercontent.com/19747913/179387669-0b9da8fb-4052-401d-9851-f409618cfb5d.png)

2022-07-17 07:40 UTC, dotoleeoak commented on frontend/src/common/components/Organism/PaginationTable.vue
> +        <template v-for="(row, index) in items" v-else :key="index">
https://vuejs.org/style-guide/rules-essential.html#avoid-v-if-with-v-for
`v-for`과 `v-if`는 같이 쓰는 걸 피해야합니다~!
엄밀히 말하면 이 경우에는 문제가 되지 않긴 한데, 유지보수성 생각해서 explicit하게 분리하는 게 좋을 것 같아요.

```html
<template v-else>
  <tr v-for="...">
```

2022-07-17 07:40 UTC, dotoleeoak commented on frontend/src/common/components/Organism/PaginationTable.vue
> +  }[]
제 생각엔 `fields`는 key, label 구분 없이 그냥 string array로 받아도 될 것 같은데 어떤가요?

2022-07-17 07:40 UTC, dotoleeoak commented on frontend/src/common/components/Organism/PaginationTable.vue
> +  }[]
`items`의 key가 fields 값이고, value(any type)가 표시될 내용인 상황인데,
사실 value는 이 component 자체에서는 쓰이지 않으니까 key만 받아도 될 것 같아요.
그렇게 되면 `row-clicked` event emit할 때 Object 전체 대신 index만 emit하는 방향으로 구현하면 되겠죠?

2022-07-17 07:40 UTC, dotoleeoak commented on frontend/src/common/components/Organism/PaginationTable.vue
> +        v-bind="$attrs"
description에서도 언급하신 것처럼, `$attrs`는 여기선 side effect가 좀 있어서, 다른 방법 쓰는 게 좋을 것 같아요.
Vue 3의 provide / inject라는 기능도 있는데, 여기서는 굳이 쓸 필요 없을 것 같고 그냥 가장 간단한 방법으로 직접 listener 달고 다시 emit 하는 방향이 좋아보여요.
구현 logic도 단순하고, `row-clicked`랑 `change-page` event의 interface가 같으면(즉, 사용 방법이 같으면) parent에서 handler 구현하는 것도 좀 더 원활할 것 같아요.

2022-07-18 02:25 UTC, goo314 commented on frontend/src/common/components/Organism/PaginationTable.vue
> +  }[]
좋을 것 같아용~!! 근데 사실 table은 저번 프로젝트에서 고대로 가져온 부분이긴 한데, 솔비팀장님이 저 fields에서 key값이 api로 요청할 params고 label은 key값 대신 사용자에게 보여질 값이라고 하더라구요..? 예를 들면, 백엔드에서 created_time으로 저장되어 있는 값을 사용자에게는 created로만 보여주는 경우! 그래서 api로 가져온 값들을 쉽게 table로 만들기 위해서 사용했다고 하는데 string array로 받아도 동작이 잘 될지 모르겠어요 (api부분은 잘 모르는데, key랑 label이 다른 위 예시처럼 created로 field값을 받고, slot 이름을 created라고 주면 부모 컴포넌트에서 해당 값을 찾을 수 있을지...?) 😖

2022-07-18 02:26 UTC, goo314 commented on frontend/src/common/components/Organism/PaginationTable.vue
> +  }[]
오오 안그래도 저 any가 마음에 걸렸었는데 곧 수정해보도록 하겠습니다~!

2022-07-18 06:06 UTC, goo314 commented on frontend/src/common/components/Molecule/Pagination.vue
> +</template>
@SOLBI1028

2022-07-18 06:38 UTC, goo314 commented
억 실수로 index.vue까지 같이 commit 올려버렸는데
아직 안고친 comment 수정하고 지우고 다시 커밋할게요 ㅠㅠ

2022-07-18 07:31 UTC, SOLBI1028 commented on frontend/src/common/components/Organism/PaginationTable.vue
> +  }[]
제가 key랑 label을 따로 둔 이유가 성현이가 설명 해준 이유가 맞아요..! 백엔드에서 사용하는 필드명과 프론트에서 테이블 헤더에 사용하는 필드 명이 다를 경우가 한번씩 생기더라구요. id같은 경우에 id가 아니라 #로 사용하거나, notice table에서 create time이 아니라 date로 사용하는 것 처럼요!
성현이가 말한 것 처럼 field 값(key)만을 string으로 받고, slot으로 대체해도 구현이 가능할 것 같긴한데, 제가 key, label 방식이 익숙해서 그런지 두가지를 설정해주는게 더 와닿네요..! 😅 해당 컴포넌트를 사용할 때에도 따로 template을 사용하는 것보단 key에 해당하는 label을 동시에 적용해주는게 더 편할것 같기도 하구요..! 
아니면 혹시 더 편하게 구현할 방법이 있을까요?!

2022-07-18 08:02 UTC, SOLBI1028 commented on frontend/src/common/components/Molecule/Pagination.vue
> +</template>
지금 디자인 되어 있는 것 보다 예시로 들어주신 pagination이 훨씬 더 편리하게 사용할 수 있을것 같아서 수정하면 좋을 것 같네요!
현재는 페이지수가 4개 이상이면 3개씩 끊고 현재 페이지에 해당하는 섹션을 보여주는 것 같은데, 3개씩 고정적으로 섹션을 나누지 말고 현재 페이지를 기준으로 currentPage-1, currentPage, currentPage+1 이런식으로 세 페이지를 보여주고, currentPage-1 이전 페이지나 currentPage+1 이후 페이지가 존재하면 Github, Amazon 예시처럼 ...으로 표시해주면 어떨까요?

2022-07-18 11:17 UTC, goo314 commented on frontend/src/common/components/Molecule/SearchBar.story.vue
> +    <SearchBar placeholder="keywords" />
추가했습니다!

2022-07-18 11:22 UTC, goo314 commented on frontend/src/common/components/Organism/PaginationTable.vue
> +        v-bind="$attrs"
중간 컴포넌트에서 하위 컴포넌트 emit을 받아 다시 상위 컴포넌트로 emit을 보내는 코드를 짰는데 이렇게 하는게 맞을까요? 😲

2022-07-18 11:29 UTC, goo314 commented on frontend/src/common/components/Molecule/Pagination.vue
> +</template>
저는 Amazon 디자인이 좋은 것 같아요~! 제일 첫페이지랑 끝페이지, 현재페이지 근처의 3페이지 보여주는게 이뻐보여요😍
근데 Amazon에서 제일 첫 1페이지랑 마지막 20번 페이지는 클릭이 되지 않던데 스꾸딩에서는 클릭할 수 있게 하는 건 어떨까요~?

2022-07-18 12:07 UTC, SOLBI1028 commented on frontend/src/common/components/Molecule/Pagination.vue
> +</template>
저는 좋은 것 같습니다~!~

2022-07-19 06:53 UTC, dotoleeoak commented on frontend/src/common/components/Organism/PaginationTable.vue
> +  }[]
그럼 API data의 key 값이 실제 보여지는 값이랑 다르니까, label이랑 key는 따로 둬도 괜찮을 것 같아요.
대신에 지금처럼 slot 쓰는 방식 대신에 아래처럼 구현해보는건 어떨까요?
(참고: Quasar의 `q-table`, https://quasar.dev/vue-components/table)

예시를 하나 들어볼게요.
key는 `id, name, created_at`이고 label은 `#, Name, Created At`인 데이터가 있다고 할게요.
API 서버에서 받은 JSON 데이터는 이렇다고 하고요.

```json
[
  { "id": 1, "name": "Apple", "created_at": "2022-04-01" },
  { "id": 2, "name": "Banana", "created_at": "2022-05-01" },
  { "id": 3, "name": "Orange", "created_at": "2022-06-01" }
]
```

table에는 아래처럼 보여주겠죠.

| # | Name | Created At |
|--------|---------|---------|
| 1 | Apple | 2022-04-01 |
| 2 | Banana | 2022-05-01 |
| 3 | Orange | 2022-06-01 |

그리고 component는 아래처럼 쓰이게 하면 slot이 따로 필요 없겠죠?
실제 구현은 `v-for`만으로도 할 수 있겠죠.

```vue
<PaginationTable
  :fields="fields"
  :items="items"
/>
```

```js
const fields = [
  { key: 'id', label: '#' },
  { key: 'name', label: 'Name' },
  { key: 'created_at': label: 'Created At' }
]

const items = [
  { id: 1, name: "Apple", created_at: "2022-04-01" },
  { id: 2, name: "Banana", created_at: "2022-05-01" },
  { id: 3, name: "Orange", created_at: "2022-06-01" }
]
```

2022-07-19 06:57 UTC, dotoleeoak commented on frontend/src/common/components/Organism/PaginationTable.vue
> +        v-bind="$attrs"
넵 좋습니다~

2022-07-19 06:57 UTC, dotoleeoak commented
main 브랜치 내용 merge해뒀습니다~

2022-07-19 09:07 UTC, goo314 commented on frontend/src/common/components/Molecule/Pagination.vue
> +</template>
수정했습니다~! 일부러 페이지 버튼 5개씩 보이도록 코드를 짰어요
코드가 조금 지저분해서 코드 깔끔하게 바꿀 수 있는 팁! 부탁 드려요 🥺

2022-07-19 09:15 UTC, dotoleeoak commented on frontend/src/common/components/Organism/PaginationTable.vue
> +  }[]
넵 아래 껀무시해주세요~

2022-07-20 12:54 UTC, goo314 commented on frontend/src/common/components/Organism/PaginationTable.vue
> +  }[]
slot을 없애고 slot자리에 바로 데이터 값이 들어가도록 수정했습니다~!

2022-07-21 04:23 UTC, goo314 commented on frontend/src/common/components/Organism/PaginationTable.vue
> +  }[]
생각해보니 slot을 없앨 수는 없겠더라구요 ..?
아래 사진을 보면 왼쪽에는 테이블에 level을 표시할때 원이 들어가고 오른쪽에는 버튼이랑 스위치가 들어가더라구요 🥶

<img width="300" alt="image" src="https://user-images.githubusercontent.com/62930375/180129260-ff4741cc-1adc-4335-b097-2560e6a971a0.png">  <img width="300" alt="image" src="https://user-images.githubusercontent.com/62930375/180129276-8627ee5d-3c57-401c-a2aa-02e8ad95dee5.png">

2022-07-22 11:59 UTC, goo314 commented
SearchBar 왼쪽에 option이름의 slot을 추가했습니다~ 사용 용도는 아래 이미지와 같이 라디오나 스위치를 넣을 수 있어요 😉

<img width="300" alt="image" src="https://user-images.githubusercontent.com/62930375/180433867-8718cb5d-6541-4e13-94d6-9a3b9d4450b8.png">    <img width="330" alt="image" src="https://user-images.githubusercontent.com/62930375/180433907-a0923d69-604f-4008-8189-b24bd903b045.png">


그리고 prop으로 item 대신 item의 개수를 받아 각 row는 slot으로 구성되어 있고 index가 binding되게 해놓은 상태입니다
부모 컴포넌트에서 row에 자유롭게 쓸 수 있는 구조로 갔습니다 

초기 파일이랑 조금 많이 바껴서(특히 Pagination 쪽) 코드 다시 봐주시면 감사하겠습니다 😘

2022-07-27 01:04 UTC, dotoleeoak commented on frontend/src/common/components/Organism/PaginationTable.story.vue
> +]
보여줄 페이지가 100페이지까지 있다고 하면 보여줄 데이터가 엄청 많아지고, API 서버에서 데이터를 받는 데에도 오래 걸리겠죠? 그래서 보통 처음에 데이터를 다 받기보단 지금 보여주는 페이지의 데이터만 받아와요.
여기서 `items`가 크기가 크진 않지만, 실제 사용할 경우를 고려해서 미리 페이지별로 데이터를 나눠놓는게 좋을 것 같아요. 예를 들어서 아래처럼요.

```ts
const items = [
  [
    { name: 'Apple', color: 'red' },
    { name: 'Banana', color: 'yellow' },
    { name: 'Car', color: 'blue' }
  ],
  [
    { name: 'Dog', color: 'brown' },
    ...
  ]
  ...
]

2022-07-27 01:04 UTC, dotoleeoak commented on frontend/src/common/components/Organism/PaginationTable.vue
> +  }[]
그러면 slot 내에 default로는 value 값을 보여주고, 다른 component를 보여줘야하는 field만 slot을 사용해서 보여주게 하는 건 어떤가요? id처럼 딱히 slot이 필요하지 않은 부분은 쓰지 않아도 되게끔 말이죠...?

2022-07-27 09:52 UTC, goo314 commented on frontend/src/common/components/Organism/PaginationTable.vue
> +  }[]
좋아요~! field에 `custom` prop을 추가해서 custom이 true일 경우 slot을 쓸 수 있게 수정하였습니다! 어떤가요?

2022-07-27 09:55 UTC, goo314 commented on frontend/src/common/components/Molecule/Pagination.vue
> +</template>
오 반영했고 조금 수정한 부분도 있습니다~!
조금 아쉬운 점은 전체 페이지가 4개일 경우 1페이지를 클릭하면 (1, 2, ..., 4) 로 나오는데 
2와 4 사이에 3밖에 없음에도 '...'이 뜬다는 거...? 괜찮나요?

2022-07-27 09:56 UTC, goo314 commented on frontend/src/common/components/Molecule/Pagination.vue
> +    >
diabled를 해도 버튼의 기본 속성 hover 기능이 남아있어 
해당 페이지일 경우 pointer-events-none 스타일을 주었습니다!

2022-07-27 09:57 UTC, goo314 commented on frontend/src/common/components/Organism/PaginationTable.story.vue
> +]
오호오호 사실 filter함수 추가하면서 이중배열이 다루기 어려워서 코드를 짰었는데 🤣
이부분도 수정했습니다~!

2022-08-02 12:24 UTC, dotoleeoak commented on frontend/src/common/components/Organism/PaginationTable.vue
> +              <slot v-else :name="field.key" :row="row"></slot>
75~76 라인 이렇게 줄이면 `field.custom`이 필요없을 거 같은데 어떤가요?

```vue
<slot :name="field.key" :row="row">{{ row[field.key] }}</slot>
```

2022-08-02 12:24 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/Pagination.vue
> +</template>
음 그 경우는 생각 못했는데 추가해둬야겠네요...

2022-08-02 12:34 UTC, goo314 commented on frontend/src/common/components/Organism/PaginationTable.vue
> +              <slot v-else :name="field.key" :row="row"></slot>
아하 slot에 default값을 줄 수 있군여! 
바로 수정하겠습니다 😆

2022-08-02 12:43 UTC, goo314 commented on frontend/src/common/components/Organism/PaginationTable.vue
> +              <slot v-else :name="field.key" :row="row"></slot>
수정했습니다!

2022-08-02 14:42 UTC, dotoleeoak commented
component 구조를 조금 더 고칠 수 있을 거 같긴 한데, 이건 고민이 더 필요할 거 같기도 하고 지금은 이 PR merge가 조금 급한 관계로 나중에 수정하겠습니다~!

2022-08-02 14:42 UTC, dotoleeoak approved these changes
수고하셨습니다~!

2022-08-03 07:16 UTC, merged