feat(fe): add carousel component
skkuding/next pull request #137
Opened 2022-07-20 07:59 UTC by hbsongk

### Description

- Carousel 구현 (#119)
### Additional context

- props
  - slides: 슬라이드에 들어갈 이미지 src 리스트
 
- data
  - direction: 움직이고자 하는 방향 left or right, transition effect name을 정의하기 위한 요소로 쓰임.
  - currentSlide: 현재 슬라이드의 위치
  - slideInterval: 슬라이드간 이동시간

- method
  - setCurrentSlide: 현재 슬라이드 위치 update
  - prev: step을 -1로 지정해주고, step + currentSlide를 해주어, 이전 슬라이드로 이동하게 해줌
  (0번째 슬라이드는 -> 마지막 슬라이드로 이동)  / 후에 startSlideTimer() 메소드 실행
  - _next: step을 1로 지정해주고, step + currentSlide를 해주어, 다음 슬라이드로 이동하게 해줌
  (마지막 슬라이드는 -> 0번째 슬라이드로 이동)  / 
  - next: _next메소드 실행 이후, startSlideTimer() 메소드 실행
  - startSlideTimer: 슬라이드를 자동으로 우측으로 이동하게 해줌.
  - stopSlideTimer: 슬라이드 동작을 멈추게 해줌.
  - switchSlide: carousel 버튼을 클릭했을시, 해당 슬라이드로 이동하게 해줌.

- 추가기능
  - `@mouseenter와 @mouseout`을 사용하여, 
  마우스가 carousel 사진위에 올라갔을시 -> 슬라이드 이동 멈춤
  마우스가 carousel 사진위에서 벗어났을시 -> 슬라이드 이동 재개

- 논의사항
  - 해당 슬라이드의 direction이 right or left인지에 따라 transition태그의 name에 차이를 두어, 
  `.slide-in-enter-active, .slide-in-leave-active` etc..와 같은 효과를 주었는데, 
  tailwind css로는 어떻게 구현해야될지 감이 잘 잡히지 않습니다.. 도와주세용!!
  
  
### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [] Ideally, include relevant tests that fail without this PR but pass with it.

2022-07-20 13:45 UTC, goo314 commented on frontend/src/home/components/Carousel.vue
> +          <img :src="slide" />
제일 위에서 설명한 것 처럼 img태그! `class="w-full h-full"` 값으로 해주세요~ 
그래야 부모컴포넌트를 꽉 채우는 이미지가 나타난답니다 😉

2022-07-21 02:38 UTC, dotoleeoak commented
main 브랜치 merge해뒀습니다~

2022-07-21 02:46 UTC, dotoleeoak requested changes

2022-07-21 02:46 UTC, dotoleeoak commented on frontend/src/home/components/Carousel.vue
> +}
[vueuse의 `useIntervalFn`](https://vueuse.org/shared/useIntervalFn/)을 사용하면 좀 더 쉽게 구현할 수 있을 것 같아요

2022-07-21 02:46 UTC, dotoleeoak commented on frontend/src/home/components/Carousel.vue
> +let direction = ref('right')
ref 할당된 변수들은 `.value`의 값이 변하고 변수 자체는 변하지 않기 때문에 const로 할당하는 게 좋습니다~!

2022-07-21 02:46 UTC, dotoleeoak commented on frontend/src/home/components/Carousel.vue
> +let direction = ref('right')
추가로 `slideInterval`은 reactivity가 필요한 변수가 아니니까 그냥 `let slideInterval = 0`으로 할당해도 될 것 같아요

2022-07-21 02:46 UTC, dotoleeoak commented on frontend/src/home/components/Carousel.vue
> +      >
제가 보기에 transition 이용한 건 좋은 선택인 것 같아요
다만 `:key` attribute는 여기 대신 `img` tag에 넣어야 잘 동작될 거에요.
그렇게 하면 `v-for`로 모든 이미지를 DOM에 등록하는 대신에, 그냥 현재 이미지만 등록해도 애니메이션이 잘 적용될 거에요.

2022-07-21 02:46 UTC, dotoleeoak commented on frontend/src/home/components/Carousel.vue
> +})
method 개수가 꽤 많아 보이는데, 지금보다 줄일 수 있을 것 같습니다...!

2022-07-22 02:56 UTC, hbsongk commented on frontend/src/home/components/Carousel.vue
> +          <img :src="slide" />
오오오 감사합니다!! 확실히 배치하는 부분이 어렵군요. 공부를 더 해보아야겠습니다!! 꾸님이 말씀하신부분들 수정완료했습니다.

2022-07-22 02:56 UTC, hbsongk commented on frontend/src/home/components/Carousel.vue
> +          @click="switchSlide(index)"
수정완료했습니닷!!

2022-07-22 02:56 UTC, hbsongk commented on frontend/src/home/components/Carousel.vue
> +    <div class="relative h-[400px] w-[900px] overflow-hidden">
수정완료했습니닷!!

2022-07-22 11:27 UTC, hbsongk commented on frontend/src/home/components/Carousel.vue
> +      >
```
      <transition
        :name="transitionEffect"
        class="absolute inset-0"
        @mouseenter="stopSlideTimer"
        @mouseout="startSlideTimer"
      >
        <div>
          <img
            :key="`item-${currentSlide}`"
            :src="slides[currentSlide]"
            class="h-full w-full"
          />
        </div>
      </transition>
```
재민님 안녕하세요! 재민님이 말씀하신거 토대로 이런식으로 한번 코드를 수정해보았는데요.
이렇게 하는게 혹시 맞나요!? 저렇게 코드를 한번 돌려보니까 transition이 따로 적용이 안되는것
같아서 확인을 해보니

transition태그 내에 ```:name="transitionEffect"```이 부분에서 computed를 호출해서 정의해놓은 
transition 속성을 먹이는데.  v-for문이 없으니 따로 transitionEffect가 먹지 않는것 같습니다 ㅜㅜ
방법이 있을까요??

2022-07-22 11:27 UTC, hbsongk commented on frontend/src/home/components/Carousel.vue
> +      >
> 제가 보기에 transition 이용한 건 좋은 선택인 것 같아요 다만 `:key` attribute는 여기 대신 `img` tag에 넣어야 잘 동작될 거에요. 그렇게 하면 `v-for`로 모든 이미지를 DOM에 등록하는 대신에, 그냥 현재 이미지만 등록해도 애니메이션이 잘 적용될 거에요.

```
      <transition
        :name="transitionEffect"
        class="absolute inset-0"
        @mouseenter="stopSlideTimer"
        @mouseout="startSlideTimer"
      >
        <div>
          <img
            :key="`item-${currentSlide}`"
            :src="slides[currentSlide]"
            class="h-full w-full"
          />
        </div>
      </transition>
```
재민님 안녕하세요! 재민님이 말씀하신거 토대로 이런식으로 한번 코드를 수정해보았는데요.
이렇게 하는게 혹시 맞나요!? 저렇게 코드를 한번 돌려보니까 transition이 따로 적용이 안되는것
같아서 확인을 해보니

transition태그 내에 ```:name="transitionEffect"```이 부분에서 computed를 호출해서 정의해놓은 
transition 속성을 먹이는데.  v-for문이 없으니 따로 transitionEffect가 먹지 않는것 같습니다 ㅜㅜ
방법이 있을까요??

2022-07-22 12:18 UTC, goo314 commented on frontend/src/home/components/Carousel.vue
> +      >
고거슨..! 아래 문서에 보면 `v-if`나 `v-show`를 넣어야 enter과 leave를 인식하는 것 같아요
근데 `v-for`을 없앤다면 `v-show`에 어떤 조건문이 들어가야 될까요? 🤔

[Transition | Vue.js](https://vuejs.org/guide/built-ins/transition.html#the-transition-component)

<img width="662" alt="image" src="https://user-images.githubusercontent.com/62930375/180437115-0ddbf0a8-30c2-4354-93d7-ad2004b5fd20.png">

2022-07-22 15:23 UTC, goo314 commented on frontend/src/home/components/Carousel.vue
> +})
vueuse를 사용하여 함수 개수를 대폭 줄였습니다~! 😉

근데 다음 슬라이드로 넘어가는 순간 바로 이전 슬라이드 버튼을 누르면 살짝 흰 부분이 보이더라구요 
일단 버튼 위로 마우스가 올라갔을때 pause를 하도록 했는데 
만약 버튼 사이에 마우스를 올려 놓다가 진짜 민첩한 사람이 위 행동을 했을 경우 흰 부분이 아직도 보이기는 해요
이 부분은 어떻게 수정해야 할까요? 아니면 이대로 놔두어도 괜찮은지 궁금합니당 🥺

2022-07-22 15:33 UTC, goo314 commented on frontend/src/home/components/Carousel.vue
> +    <div class="relative h-[400px] w-[900px] overflow-hidden">
오 수정사항 보긴 했는데 약간 고민이에요 피그마에 설정된 값으로 부탁드렸는데 생각보다 너무 큰 것 같기도 하고 🤭

2022-07-22 16:37 UTC, goo314 commented
그... CI를 통과를 못했는데, 제가 @vue/core를 지우고? 깔아서 꼬인 것 같아요 😱 어떻게 해야되나요?

2022-07-27 01:22 UTC, dotoleeoak commented on frontend/src/home/components/Carousel.vue
> +      >
`v-if`나 `v-show`로도 trigger가 되긴 하지만, `key`로도 trigger할 수 있습니다...!
`v-for`에서 쓰는 `key`처럼 여기서도 `key`에 해당하는 reactive(ref) 값이 변경되면 vue가 인식하는 원리죠.
다만 `key`는 `transiton`의 child component에 있을 때만 인식되기 때문에 홍빈님 코드에선 `div`에 감싸져 있어서 인식이 안됐던 것 같아요.

아래처럼 짜면 될 것 같습니다~!

```vue
<transition
  :name="direction"
  class="absolute inset-0"
  @mouseenter="pause"
  @mouseout="resume"
>
  <img :key="currentSlide" :src="slides[currentSlide]" />
</transition>
```

2022-07-27 01:25 UTC, dotoleeoak commented on frontend/src/home/components/Carousel.vue
> +})
음... reproduction이 안되는데 캡처본 같은거 보여주실 수 있나요?

2022-07-27 13:43 UTC, goo314 commented on frontend/src/home/components/Carousel.vue
> +})
[Screen Recording 2022-07-27 at 10.39.03 PM.zip](https://github.com/skkuding/next/files/9199372/Screen.Recording.2022-07-27.at.10.39.03.PM.zip)
동영상 녹화했어요오

2022-07-27 15:39 UTC, goo314 commented on frontend/src/home/components/Carousel.vue
> +      >
오오오 새로운걸 배워갑니다~~!
( 문서에 없는데 그런 정보는 어디서 찾아오시는 건가요? 😲 )

후딱 수정했습니다!

2022-08-08 23:34 UTC, dotoleeoak commented
이미지 비율이 고정이 안돼서 배경에 blur 효과 추가하였습니다~!

### Desktop
![image](https://user-images.githubusercontent.com/19747913/183531588-aab7a17f-8591-4980-983e-3d09f8272ce9.png)

### Mobile
![image](https://user-images.githubusercontent.com/19747913/183531937-2505fed0-213e-48d5-b8fe-c2e2d46747fd.png)

2022-08-08 23:36 UTC, dotoleeoak commented on frontend/src/home/components/Carousel.vue
> +})
@goo314 혹시 지금도 증상 똑같이 있나요?

2022-08-08 23:42 UTC, dotoleeoak commented on frontend/src/home/components/Carousel.vue
> +    <div class="relative h-[400px] w-[900px] overflow-hidden">
반응형으로 높이 적용해뒀습니다~!

2022-08-08 23:42 UTC, dotoleeoak approved these changes

2022-08-12 15:54 UTC, goo314 commented on frontend/src/home/components/Carousel.vue
> +})
오 없어졌어요!! 😲 왕 정말 감사합니다

2022-08-12 16:26 UTC, merged