feat(fe): add modal component
skkuding/next pull request #143
Opened 2022-07-22 07:46 UTC by Kohminchae

### Description

- modal component 구현
- close #124 
- slot으로 학교 로고 등 이미지 추가 가능
- slot으로 모달 내용 추가 가능

2022-07-23 09:07 UTC, SOLBI1028 requested changes

2022-07-23 09:07 UTC, SOLBI1028 commented on frontend/src/common/components/Molecule/Modal.vue
> +    </div>
`<div>`태그는 빼도 될 것 같아요~!

2022-07-23 09:07 UTC, SOLBI1028 commented on frontend/src/common/components/Molecule/Modal.vue
> +</template>
사용하는 modal 대부분에서 하단에 yes / no 버튼을 사용하고 있어서 추가를 해두고 사용할지 말지 여부를 선택하도록 해도 좋을 것 같은데, 어떻게 생각하시나요?
사용하지 않는 모달들도 여러개 있어서 고민이 되긴 하네요 😅 의견 말해주시면 감사하겠습니당~!~!!~

2022-07-26 11:55 UTC, goo314 commented on frontend/src/common/components/Molecule/Modal.vue
> +</template>
오 있으면 좋을 것 같아요~! 사용자가 정말로 이 선택을 할 것인지 물어보는 모달이 생각보다 많더라구요
prop으로 boolean값을 받아서 true면 yes, no 버튼을 보여주면 좋을 것 같아요
아니면 yes, no 가 아니더라도 버튼은 아래쪽에 위치하니까 slot을 모달 아래쪽에 위치하도록 추가해서 
버튼을 1개, 2개 사용자가 커스텀하는 것도 나쁘지 않을 것 같아요 😆

2022-07-29 07:48 UTC, SOLBI1028 approved these changes

2022-07-29 13:04 UTC, merged