feat(be): implement user CRUD api
skkuding/next pull request #155
Opened 2022-07-27 12:27 UTC by minseo999

### Description

Resolves #140 
- `signUp()`: 필수 정보를 받아 회원 가입을 합니다.
  - User 생성, UserProfile 생성, Public Group에 추가 
- `withdrawal()`: 계정 탈퇴 기능입니다.
  - 계정 password를 받아 유효성, 권한 검사 후 계정을 삭제합니다. 
- `getUserProfile()`: 프로필 페이지에서 보여줄 회원 정보를 받아옵니다.
  - username, role, email, last_login, update_time, real_name 한정적인 정보만 응답합니다.
- `updateUserRealName()`: UserProfile의 real_name을 변경하는 기능입니다.
- `updateUserEmail()`: 이메일 인증 후, 계정의 이메일을 변경하는 기능입니다.

### Additional context

- User와 UserProfile 데이터 중 사용자가 update할 수 있는 것은 email, real_name 두 field라고 생각해서 update 기능은 두 field에 대해서만 구현했습니다.
- `signUp()`과 `updateUserEmail()`은 #109 가 완료되면 구현하겠습니다.

**논의하고싶은 부분**
- username과 password의 제약사항을 설정하는 것이 좋을 것 같습니다.
  - 글자 수 min, max 제한/특수문자 포함여부/대소문자 구분 여부
- 기존에는 username을 학번으로 제한했었는데 그러면 학번이 없는 교수님들께서 가입이 제한될 것 같아 username은 로그인을 위한 id로 사용하려고 합니다. username 외에 UserProfile에 학번 field가 필요할까요?
---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-12-22 15:46 UTC, SH9480P requested changes

2022-12-23 07:04 UTC, SH9480P commented
**논의하고싶은 부분**

> username과 password의 제약사항을 설정하는 것이 좋을 것 같습니다.(글자 수 min, max 제한/특수문자 포함여부/대소문자 구분 여부) 

동의합니다!
username 글자 수는 3-10자, 알파벳과 숫자만 허용, 소문자로 통일 정도가 어떨까요?
password는 8-64자로 하고 모든 문자를 허용하게 하면 안전할 것 같아요. [owasp cheetsheet](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls)을 참고했습니다.

<br>

> 기존에는 username을 학번으로 제한했었는데 그러면 학번이 없는 교수님들께서 가입이 제한될 것 같아 username은 로그인을 위한 id로 사용하려고 합니다. username 외에 UserProfile에 학번 field가 필요할까요?

#198에서 studentId를 추가했습니다.

2022-12-23 07:19 UTC, aintbe commented on backend/src/user/user.service.ts
> +
비밀번호 암호화 수준 검사하는 로직 추가해주세요!
- 비밀번호 8자 이상, 대문자/소문자/숫자/특수기호 중 2가지 이상의 조합

2022-12-23 07:31 UTC, aintbe commented on backend/src/user/user.service.ts
> +      rejectOnNotFound: () => new EntityNotExistException('User')
다른 PR에서는 소문자로 처리되어 있어서, 소문자로 통일하는 게 좋을 것 같아요!

2022-12-23 07:31 UTC, aintbe commented on backend/src/user/user.service.ts
> +      rejectOnNotFound: () => new EntityNotExistException('UserProfile')
소문자로 통일해주세요!

2022-12-23 08:28 UTC, aintbe commented on backend/src/user/user.service.ts
> +  }
2. `createJwt(payload)`는 서비스단에서 호출해서 JWT 토큰을 만드는 로직이기 때문에 email만 인자로 받아서 처리하는 게 가능하지만, 이 함수는 토큰이 들어있는 request를 받아서 여기서 파싱하는 과정(`verifyJwtFromRequestHeader()`)이 필수적이기 때문에 이걸 서비스 앞단에서 넣어주기는 어려울 것 같아요!

2022-12-23 11:31 UTC, aintbe commented
> username 글자 수는 3-10자, 알파벳과 숫자만 허용, 소문자로 통일 정도가 어떨까요? password는 8-64자로 하고 모든 문자를 허용하게 하면 안전할 것 같아요. [owasp cheetsheet](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls)을 참고했습니다. @SH9480P

다음과 같은 validation 로직을 `signUp` 및 `updatePassword`에 추가했습니다.
- `isValidUsername`
  + 3-10자
  + 알파벳 소문자, 숫자 중 1가지 이상의 조합
- `isValidPassword`
  + 8-64자
  + 알파벳 소문자, 알파벳 대문자, 숫자, 특수기호 중 2가지 이상의 조합

2022-12-23 13:42 UTC, aintbe requested changes
이 PR에서 작성된 코드에 대한 테스트케이스가 없어서 필요한 부분에 주석을 달았습니다! 완벽하게 확인하고 단 것이 아니라 주석이 달려 있지만 실제로는 테스트케이스 작성이 필요없는 경우가 있을 수 있습니다.

2022-12-23 13:42 UTC, aintbe commented on backend/src/user/user.service.ts
> +  async sendPinForPasswordReset({ email }: UserEmailDto): Promise<string> {
테스트케이스 작성

2022-12-23 13:42 UTC, aintbe commented on backend/src/user/user.service.ts
> +  async sendPinForRegisterNewEmail({ email }: UserEmailDto): Promise<string> {
테스트케이스 작성

2022-12-23 13:42 UTC, aintbe commented on backend/src/user/user.service.ts
> +    if (!this.isValidPassword(newPassword)) {
잘못된 password를 넘겨준 경우에 대한 테스트케이스 작성

2022-12-23 13:42 UTC, aintbe commented on backend/src/user/user.service.ts
> +  async verifyPinAndIssueJwt({
테스트케이스 수정

2022-12-23 13:42 UTC, aintbe commented on backend/src/user/user.service.ts
> +  async signUp(signUpDto: SignUpDto, req: Request): Promise<User> {
테스트케이스 작성

2022-12-23 13:42 UTC, aintbe commented on backend/src/user/user.service.ts
> +    }
잘못된 username or password가 전달되었을 때의 테스트케이스 작성

2022-12-23 13:42 UTC, aintbe commented on backend/src/user/user.service.ts
> +  async createUser(signUpDto: SignUpDto): Promise<User> {
테스트케이스 작성

2022-12-23 13:42 UTC, aintbe commented on backend/src/user/user.service.ts
> +  async createUserProfile(
테스트케이스 작성

2022-12-23 13:42 UTC, aintbe commented on backend/src/user/user.service.ts
> +  async registerUserToPublicGroup(userId: number) {
테스트케이스 작성

2022-12-23 13:42 UTC, aintbe commented on backend/src/user/user.service.ts
> +  async withdrawal(username: string, withdrawalDto: WithdrawalDto) {
테스트케이스 작성

2022-12-23 13:42 UTC, aintbe commented on backend/src/user/user.service.ts
> +  async deleteUser(username: string) {
테스트케이스 작성

2022-12-23 13:42 UTC, aintbe commented on backend/src/user/user.service.ts
> +  async getUserProfile(username: string): Promise<GetUserProfileDto> {
테스트케이스 작성

2022-12-23 13:42 UTC, aintbe commented on backend/src/user/user.service.ts
> +  async updateUserEmail(
테스트케이스 작성

2022-12-23 13:42 UTC, aintbe commented on backend/src/user/user.service.ts
> +  async updateUserProfileRealName(
테스트케이스 작성

2023-01-02 16:27 UTC, SH9480P commented
전에 main 브랜치를 merge하면서 #205 에서 구현된 부분의 일부가 날아간 모양입니다. 해당 부분을 수정했습니다.
회원가입, 이메일 변경, 비밀번호 재설정에 수반되는 이메일 내용을 email-auth로 통일하도록 구현했습니다.
각 상황에 따라 이메일 내용을 달리 보여주고 싶다면 코드를 수정해야 합니다.

2023-01-17 14:13 UTC, aintbe approved these changes

2023-01-20 06:56 UTC, SH9480P approved these changes
오타만 수정하고 merge해주세요! 수고하셨습니다🥇

2023-01-20 06:56 UTC, SH9480P commented on backend/src/group/interface/user-group-data.interface.ts
> +}
isRegister'ed' 오타났어요

2023-01-20 06:56 UTC, SH9480P commented on backend/src/group/group.service.ts
> +  }
userGroupData.isRegisterd 오타났어요

2023-01-20 06:56 UTC, SH9480P commented on backend/src/user/user.service.ts
> +    await this.groupService.createUserGroup(userGroupData)
isRegisterd 오타났어요 🦘

2023-01-26 11:58 UTC, merged