feat(be): implement a group contest switch to public request
skkuding/next pull request #179
Opened 2022-08-04 13:08 UTC by minseo999

### Description

[GroupManager]
- `createContestToPublicRequest`: contest를 public으로 전환하는 request를 전송합니다.
- `deleteContestToPublicRequest`: public 전환 request를 취소(삭제)합니다.
- `getContestToPublicRequest`: public 전환 request를 열람합니다.

[SuperManager]
- `respondContestToPublicRequest`: public 전환 request에 응답합니다. (accept or reject)
- `getPendingContestToPublicRequests`: 응답하지 않은 request list를 가져옵니다.
- `getRespondedContestToPublicRequests`: 응답한 request list를 가져옵니다.
- `getContestToPublicRequest`: request 세부사항을 열람합니다.

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-08-16 07:42 UTC, cranemont requested changes

2022-08-16 07:42 UTC, cranemont commented on backend/prisma/schema.prisma
> +}
혹시 분사 형태(Pending, Accepted, Rejected)로 통일하는건 어때요?

2022-08-16 07:42 UTC, cranemont commented on backend/src/contest/contest.service.ts
> +    }
혹시 contest_id에서 unique조건을 빼고, create할때는 Pending/Accepted된 요청이 기록에 있는 경우에는 거부하고, delete할때는 Pending만 삭제할 수 있도록 하는건 어떤가요? 요청하는 측에서 reject 기록을 마음대로 지워버리면 admin쪽에서 파악이 어려울 것 같다는 생각이 들어서요..!

2022-08-16 07:55 UTC, cranemont commented on backend/src/contest/contest.service.ts
> +    }
근데 자주 쓰이는 기능이 아니기도 하고, 덮어쓴다는 개념으로 생각하면 괜찮을 것 같긴 하네요 🤔

2022-08-16 08:30 UTC, cranemont commented on backend/src/contest/contest.service.ts
> +    })
없는 리소스를 삭제하려고 할 때는 상태변화가 어차피 없으니까 예외처리를 안 해줘도 될 것 같아요..! 그럼 request를 찾는과정을 deleteUnacceptedContestToPublicRequest 안에 포함시켜서 createContestToPublicRequest의 조건검사를 해당 함수 호출로 끝내고 deleteContestToPublicRequest에서는 deleteUnacceptedContestToPublicRequest만 호출하면 될것같은데 어떻게 생각하시나요?

2022-08-16 08:31 UTC, cranemont commented on backend/src/contest/contest.service.ts
> +      })
else 빼도 될것같아요!

2022-08-16 08:33 UTC, cranemont commented on backend/src/contest/contest.service.ts
> +      },
혹시 select를 한 이유가 있을까요??

2022-08-16 08:33 UTC, cranemont commented on backend/src/contest/contest.service.ts
> +    }
await 붙여주세요!

2022-08-16 08:37 UTC, cranemont commented on backend/src/contest/contest-admin.controller.ts
> +  @Patch('/:id/topublic')
혹시 하이픈 써서 to-public으로 하는건 어떨까요?
https://stackoverflow.com/questions/10302179/hyphen-underscore-or-camelcase-as-word-delimiter-in-uris

2022-08-16 08:56 UTC, cranemont commented on backend/src/contest/contest.service.ts
> +    })
https://stackoverflow.com/questions/6439416/status-code-when-deleting-a-resource-using-http-delete-for-the-second-time
https://groups.google.com/g/api-craft/c/G0p_AGxbwuU

이것도 말이 많네요..! restful하게 작성하려면 예외처리하고 400번대 코드를 반환하는게 맞다고 하는데, 어디서는 또 상황에 따라서 적절하게 쓰라고 합니다.....🤔

2022-08-16 17:52 UTC, minseo999 commented on backend/src/contest/contest.service.ts
> +    })
저도 구현하면서 찾아봤었는데, 없는 리소스를 삭제하면 상태변화가 없어서 user가 삭제가 정상적으로 되었는지 되지 않았는지 파악할 수가 없어서 notFound 예외를 던지는게 좋다고 하더라고요! (관련 자료는 다시 찾아보고 링크 걸겠습니당)

예외처리부분을 빼면 확실히 코드가 깔끔해지기는 하는데 어떤 편이 좋을까요..

2022-08-16 17:54 UTC, minseo999 commented on backend/src/contest/contest.service.ts
> +      },
다른 부분이랑 같이 작성하다가 select 옵션이 잘못 들어갔나봐요! 수정해두겠습니다 감사합니당 😄

2022-08-17 05:40 UTC, aintbe commented on backend/src/contest/contest.service.ts
> +    })
출처는 찾아봐야겠지만 레코드 삭제 시에는 탐색 후 삭제하는 것이 기본이라고 알고 있고, 상태 변화가 없다고 해도 '삭제되지 않음'도 클라이언트가 받아야 하는 하나의 응답이라고 생각해서 저는 그대로 두는 게 좋을 것 같아요!

2022-08-17 05:40 UTC, aintbe commented on backend/src/contest/contest.service.ts
> +        'This contest is already accepted to be public'
`UnprocessableDataException`은 지금까지 요청의 형식은 옳지만 데이터상의 오류가 있을 때 throw되는 역할로 쓰여왔는데, 이 상황에서 쓰이면 역할이 너무 확장되는 것 같아요. 문법 오류가 있을 때 반환되는 UnprocessableEntity HTTP 코드의 의미와 비교해도 그렇구요!

저도 '해당 리소스(컨테스트)에 대하여 요청된 메소드를 수행할 수 없다'를 의미하는 Exception이 필요해서 찾아보다가, 서비스에서는 `ActionNotAllowedException`(business.exception.ts에 새로 정의)을 throw하고 컨트롤러에서 이것을 받으면 `MethodNotAllowedException`(nest.js 빌트인)을 throw하도록 설계했었는데 이 방식은 어떠신가요?

> [405 Method Not Allowed](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405) The request method is known by the server but is not supported by the target resource. For example, an API may not allow calling DELETE to remove a resource.

2022-08-29 15:11 UTC, mixxeo commented
@cranemont  @aintbe 
기획이 바뀌어서 description도 추가했습니다!
코드리뷰도 모두 반영했으니 확인부탁드려요!

2022-12-23 11:03 UTC, dotoleeoak approved these changes

2022-12-28 11:21 UTC, SH9480P approved these changes

2022-12-28 11:22 UTC, merged