feat(fe): add sidebar component
skkuding/next pull request #187
Opened 2022-08-10 09:50 UTC by hbsongk

### Description

group admin 페이지 왼쪽 상단에 위치할 Sidebar 메뉴입니다!
페이지에 접속하면 사이드바에 있는 해당 페이지 버튼에 라벨이 생깁니다.

![sidebar](https://user-images.githubusercontent.com/68498323/183861398-77f17863-1d2d-4932-87dd-4dc4dc156ea4.png)

### Additional context

- props
  - color : 사이드바 페이지 버튼 라벨 색상.
 
### Question

1. 이전에 #68 Button 만들때도 발생했던 issue인데, tailwind css 특성상 static한 변수만 먹히기 때문에 next project에서 `현재 다루고 있는 모든 색 요소들을 if문을 통해 받아와서 변형된 색을 return해주었습니다`. 하지만 만약 색요소들이 엄청나게 늘어나게 되면 코드가 많이 지저분해질거라고 생각되는데, 혹시 이 방법외에 보다 효율적인 방식이 있을까요??

```
const sidebarColor = computed(() => {
  if (props.color === 'blue') {
    return 'border-l-blue border-l-8 !pl-8'
  } else if (props.color === 'gray') {
    return 'border-l-gray border-l-8 !pl-8'
  } else if (props.color === 'gray-dark') {
    return 'border-l-gray-dark border-l-8 !pl-8'
  } else if (props.color === 'white') {
    return 'border-l-white border-l-8 !pl-8'
  } else {
    return 'border-l-green border-l-8 !pl-8'
  }
```
2. 처음에는 border를 사용해서 Sidebar 구현을 해볼생각이었는데, tailwind css에서 opacity를 전범위로 줄수는 있어도 `특정 border(ex border left)에만 줄수는 없었습니다` 혹시 특정 border만 속성을 줄수 있는 방법이 있을까요?

3. 추가로 border 모양자체가 height를 주었을때 일직선인 형태가 아니라 깎인 형태가 나와 외관상 이쁘지가 않아 대신 hr 태그로 구현했습니다. 더 좋은 방법 있으면 말씀해주세요!!

```      
      <router-link
        class="flex items-center p-2 pl-10 font-medium hover:shadow"
        :active-class="sidebarColor"
        to="/"
      >
        <User class="mr-2 h-4" />
        Member
      </router-link>
      <hr class="bg-gray h-px border-none opacity-25" />
```

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2022-08-10 14:03 UTC, dotoleeoak commented
혹시 png 대신 벡터 이미지(svg) 사용 가능할까요?
퍼포먼스 이유도 그렇고 재사용성도 svg가 더 좋을 것 같아서요...!

2022-08-10 14:42 UTC, dotoleeoak commented
#### Q1

우리가 Tailwind CSS를 사용하는 주된 이유 중 하나가 **'디자인 시스템'** 구축입니다. 디자인 시스템을 사용하는 이유는 색깔부터 크기, 그림자, 애니메이션 등 전반적인 요소들을 통일해 일체감을 주는 거죠. (관련된 내용은 구글링해보면 친절한 자료들 많습니다 ㅎㅎ) 그래서 이 의도에 맞춘 구현은 사실 색상 종류를 가능한 줄이는 거겠죠. 실제로 많은 웹 디자이너들이 색상 종류를 최소화하는 걸 권하기도 하고요.
만약 정 색상 종류를 늘려야 한다면 굳이 Tailwind의 class를 쓰기보단 CSS와 `v-bind`를 이용하는 게 좋아보여요. Tailwind의 class를 가급적 쓰는 게 좋은 거지, 목적에 맞지 않는 곳에도 쓰는 건 주객전도니까요.

#### Q2

제가 알기로 Border에 opacity를 적용하는 건 바닐라 CSS로도 안되는 걸로 알고 있어요. 대신에 CSS에는 alpha 값이라는 걸 적용할 수 있는데, 예를 들어서 `rgb(14 165 233/.5)`라고 하면 `.5` 부분이 alpha 값이고, opacity 50%가 적용돼요. 물론 Tailwind CSS에서도 지원하니 이걸 사용하면 될 것 같네요.

문서: https://tailwindcss.com/docs/background-color#changing-the-opacity

![image](https://user-images.githubusercontent.com/19747913/183927886-90d6e809-e8c2-4e6a-b1b8-36deec1ae600.png)

#### Q3

사실 이 질문은 잘 이해를 못 했는데... outline이나 divide도 알아보는 게 좋을 것 같습니다.
이건 추가로 답글 달아주시면 답변 드리겠습니다!

2022-08-10 14:42 UTC, dotoleeoak requested changes

2022-08-10 14:42 UTC, dotoleeoak commented on frontend/src/common/components/Organism/Sidebar.vue
> +})
이 부분은 `if else` 대신 object 이용해서 mapper를 만들어두면 가독성이 좀 더 나아질 것 같아요~!
예시: https://github.com/skkuding/next/blob/main/frontend/src/common/components/Molecule/Badge.vue

2022-08-10 14:42 UTC, dotoleeoak commented on frontend/src/common/components/Organism/Sidebar.vue
> +      </router-link>
여긴 중복되는 게 많아보이는데 `v-for` 써보는 거 어떨까요?

2022-08-11 02:44 UTC, hbsongk commented
> #### Q1
> 우리가 Tailwind CSS를 사용하는 주된 이유 중 하나가 **'디자인 시스템'** 구축입니다. 디자인 시스템을 사용하는 이유는 색깔부터 크기, 그림자, 애니메이션 등 전반적인 요소들을 통일해 일체감을 주는 거죠. (관련된 내용은 구글링해보면 친절한 자료들 많습니다 ㅎㅎ) 그래서 이 의도에 맞춘 구현은 사실 색상 종류를 가능한 줄이는 거겠죠. 실제로 많은 웹 디자이너들이 색상 종류를 최소화하는 걸 권하기도 하고요. 만약 정 색상 종류를 늘려야 한다면 굳이 Tailwind의 class를 쓰기보단 CSS와 `v-bind`를 이용하는 게 좋아보여요. Tailwind의 class를 가급적 쓰는 게 좋은 거지, 목적에 맞지 않는 곳에도 쓰는 건 주객전도니까요.
> 
> #### Q2
> 제가 알기로 Border에 opacity를 적용하는 건 바닐라 CSS로도 안되는 걸로 알고 있어요. 대신에 CSS에는 alpha 값이라는 걸 적용할 수 있는데, 예를 들어서 `rgb(14 165 233/.5)`라고 하면 `.5` 부분이 alpha 값이고, opacity 50%가 적용돼요. 물론 Tailwind CSS에서도 지원하니 이걸 사용하면 될 것 같네요.
> 
> 문서: https://tailwindcss.com/docs/background-color#changing-the-opacity
> 
> ![image](https://user-images.githubusercontent.com/19747913/183927886-90d6e809-e8c2-4e6a-b1b8-36deec1ae600.png)
> 
> #### Q3
> 사실 이 질문은 잘 이해를 못 했는데... outline이나 divide도 알아보는 게 좋을 것 같습니다. 이건 추가로 답글 달아주시면 답변 드리겠습니다!

오오 감사합니다 역시 tailwind css가 왜 생겼는지, 그 본질부터 확실하게 알고 사용하는거하고 모르는거랑은 차이가 어마어마하게 나네요. 매번 이렇게 친절하게 답글 남겨주셔서 감사합니다 :) 많이 배워갑니닷!!

2022-08-11 02:45 UTC, hbsongk commented
> > #### Q1
> > 우리가 Tailwind CSS를 사용하는 주된 이유 중 하나가 **'디자인 시스템'** 구축입니다. 디자인 시스템을 사용하는 이유는 색깔부터 크기, 그림자, 애니메이션 등 전반적인 요소들을 통일해 일체감을 주는 거죠. (관련된 내용은 구글링해보면 친절한 자료들 많습니다 ㅎㅎ) 그래서 이 의도에 맞춘 구현은 사실 색상 종류를 가능한 줄이는 거겠죠. 실제로 많은 웹 디자이너들이 색상 종류를 최소화하는 걸 권하기도 하고요. 만약 정 색상 종류를 늘려야 한다면 굳이 Tailwind의 class를 쓰기보단 CSS와 `v-bind`를 이용하는 게 좋아보여요. Tailwind의 class를 가급적 쓰는 게 좋은 거지, 목적에 맞지 않는 곳에도 쓰는 건 주객전도니까요.
> > #### Q2
> > 제가 알기로 Border에 opacity를 적용하는 건 바닐라 CSS로도 안되는 걸로 알고 있어요. 대신에 CSS에는 alpha 값이라는 걸 적용할 수 있는데, 예를 들어서 `rgb(14 165 233/.5)`라고 하면 `.5` 부분이 alpha 값이고, opacity 50%가 적용돼요. 물론 Tailwind CSS에서도 지원하니 이걸 사용하면 될 것 같네요.
> > 문서: https://tailwindcss.com/docs/background-color#changing-the-opacity
> > ![image](https://user-images.githubusercontent.com/19747913/183927886-90d6e809-e8c2-4e6a-b1b8-36deec1ae600.png)
> > #### Q3
> > 사실 이 질문은 잘 이해를 못 했는데... outline이나 divide도 알아보는 게 좋을 것 같습니다. 이건 추가로 답글 달아주시면 답변 드리겠습니다!

오오 감사합니다 역시 tailwind css가 왜 생겼는지, 그 본질부터 확실하게 알고 사용하는거하고 모르는거랑은 차이가 어마어마하게 나네요. 매번 이렇게 친절하게 답글 남겨주셔서 감사합니다 :) 많이 배워갑니닷!!

2022-08-13 07:20 UTC, goo314 commented on frontend/src/common/components/Organism/Sidebar.vue
> +      </router-link>
수정했습니다 😁

2022-09-04 06:52 UTC, goo314 commented
> 로고 svg 포맷으로 추가해뒀습니다~!

오잉 로고도 components > Atom 에 들어가나요??
페이지 상단 탭? 에 있는 로고는 assets 폴더 안에 있어서요! 😲

2022-09-04 06:53 UTC, dotoleeoak commented
> 오잉 로고도 components > Atom 에 들어가나요??
> 페이지 상단 탭? 에 있는 로고는 assets 폴더 안에 있어서요! 😲

사용하기 쉽게 svg 파일 감싼 vue component로 만들어 뒀어요~!

2022-09-04 06:59 UTC, goo314 commented
헉 칼답..! 오오옹 감사합니다 🤩

2022-09-04 07:09 UTC, goo314 commented
Story에 특정 group 페이지에 들어갔을 경우(?) 보여지는 sidebar 예시도 추가했습니다~!

2022-09-04 07:26 UTC, merged