feat(fe): add home page
skkuding/next pull request #199
Opened 2022-08-14 09:19 UTC by djc06048

### Description
#### Home page 구현

* Header 컴포넌트 수정 #126 
  * Organism에 LogInModal, SignUpModal, PasswordFindModal 컴포넌트 추가(각 모달마다 브랜치 파서 메인에 머지해야됩니다)
* modal 컴포넌트 수정 #143 
  * css 스타일 변경
#### 일반형

![image](https://user-images.githubusercontent.com/62535887/184530267-65d72884-7e6f-48c2-81b1-d1952005ca88.png)

#### 반응형

<img width="670" alt="image" src="https://user-images.githubusercontent.com/62535887/184530476-5db04cb1-eea6-499f-bc0c-dfcf3b0cb556.png">

### Required component
Header(#126)
Footer(#106)
Modal(#143 )
CardHome(#115)
Carousel(#137)

### Additional context
* Header.vue FIXME 주석 부분
  1. md이하일 경우 로그인 모달에서 Sign In 버튼 누를시 user아이콘 모양으로 바뀌지 않음 
  2. signUpModal x 버튼 안먹혀요........🥹

close #173

2022-08-17 06:33 UTC, SOLBI1028 commented
1. md 이하일 경우 로그인을 했을 때 사진과 같이 user, setting, management 아이콘으로 뜨도록 되어 있습니다!
<img width="709" alt="image" src="https://user-images.githubusercontent.com/75013515/185047799-b099f6bd-7881-4d72-8a4d-4caa12109c7a.png">

2. Signup modal 에서 x 버튼이 안눌리는건 modal title 때문에 (x 버튼을 title이 덮어버려서) 클릭이 안되는 것 같아요! (x 위쪽으로 마우스 위치시키면 커서 포인터로 바뀌면서 클릭되는거 확인하실 수 있어요)
```
<div class="absolute top-0 bottom-0 right-0 left-0 m-auto h-fit w-fit">
          <div class="mx-auto my-2 w-fit"><slot name="modal-image" /></div>
          <div class="text-bold mb-4 text-center text-xl" :class="titleStyle">
            <slot name="modal-title" />
          </div>
          <slot name="modal-content" />
</div>
<IconoirCancel
          class="text-gray absolute right-4 top-4 cursor-pointer"
          @click="$emit('close')"
/>
```
이렇게 x 버튼이 더 나중에 렌더링 되도록 (title보다 위에 위치하게) 코드 상 순서만 바꾸면 정상적으로 동작합니다!
순서를 변경하지 않고 x 버튼에 `z-50` 지정해줘도 정상동작해요!
편한 방법으로 해주시면 될 것 같습니다~!

2022-08-17 07:30 UTC, SOLBI1028 requested changes

2022-08-17 07:30 UTC, SOLBI1028 commented on frontend/src/common/components/Molecule/Modal.vue
>    titleColor?: string
title을 props가 아니라 slot으로 받고, 그 slot에 색상 등 스타일을 적용할거라면 titleColor가 없어도 될 것 같아요~!

2022-08-17 07:30 UTC, SOLBI1028 commented on frontend/src/common/components/Molecule/Modal.vue
> +          </slot>
modal title에 일관된 스타일을 적용하기 위해서 아래처럼 작성하면 좋을 것 같아요.
기존 코드에서는 모달을 사용하는 페이지에서 `<template #modal-title>` 에 스타일을 적용해주지 않고 텍스트만 전달했을 때 스타일이 적용되지 않습니다
```
<div class="text-bold mb-4 text-center text-xl" :class="titleStyle">
  <slot name="modal-title" />
</div>
```

2022-08-17 07:30 UTC, SOLBI1028 commented on frontend/src/common/components/Organism/LogInModal.vue
> +  <Modal v-if="props.visible" class="text-green h-[537px] w-[360px]">
<img width="379" alt="image" src="https://user-images.githubusercontent.com/75013515/185058781-87f72e99-c4d8-4350-b8a8-9968d090dcd2.png">
모든 모달에 `text-green`을 적용해놓으신 이유가 있을까요?
모달 전체에 연두색이 먹어서 input item에 입력하는 text도 연두색으로 나옵니다! 모달 전체에 green을 먹이는것 보다는 연두색이 필요한 곳에만 지정해주면 좋을 것 같아요!

2022-08-17 07:30 UTC, SOLBI1028 commented on frontend/src/common/components/Organism/LogInModal.vue
> +  <Modal v-if="props.visible" class="text-green h-[537px] w-[360px]">
그리고 모든 모달 크기가 피그마에 맞춰서 작성된 것 같은데, 피그마 크기는 무시하고 최대한 tailwind css에 클래스로 제공하고 있는 크기를 사용하고, 없다면 지정해주는 방식으로 가면 좋을 것 같아요!
크기는 4px 을 단위로 하는게 좋을 것 같습니다 :)

2022-08-17 07:30 UTC, SOLBI1028 commented on frontend/src/common/components/Organism/SignUpModal.vue
> +      <Button color="green" class="mb-2">register</Button>
대문자(Register)로 바꿔주세요!

2022-08-17 07:30 UTC, SOLBI1028 commented on frontend/src/common/components/Organism/LogInModal.vue
> +  <Modal v-if="props.visible" class="text-green h-[537px] w-[360px]">
input item과 아이콘 버튼을 사용할 때 세로정렬을 가운데 정렬로 맞춰주시면 좋을 것 같아요~!

2022-08-17 07:30 UTC, SOLBI1028 commented on frontend/src/home/pages/index.vue
> +      </Card>
Carousel과 카드 사이에 마진을 두면 더 보기 좋을 것 같습니다 :)

2022-08-17 07:30 UTC, SOLBI1028 commented on frontend/src/common/components/Organism/Header.vue
> +      ></PasswordFindModal>
지금 모달들의 코드상 위치가
- 화면의 크기가 md보다 클 때 header 스타일
- md일때 header 스타일
을 나타내는 코드들 사이에 들어와있어서 가독성이 조금 떨어지는 것 같아요.
모달들은 독립적으로 보여지는 컴포넌트들이니까 header.vue 코드 하단에 위치하면 좋을 것 같습니다~!

2022-08-24 01:05 UTC, djc06048 commented on frontend/src/common/components/Organism/LogInModal.vue
> +  <Modal v-if="props.visible" class="text-green h-[537px] w-[360px]">
> 그리고 모든 모달 크기가 피그마에 맞춰서 작성된 것 같은데, 피그마 크기는 무시하고 최대한 tailwind css에 클래스로 제공하고 있는 크기를 사용하고, 없다면 지정해주는 방식으로 가면 좋을 것 같아요! 크기는 4px 을 단위로 하는게 좋을 것 같습니다 :)

공식문서를 확인해보면 tailwindcss 에서는 w-96 h-96 이상의 크기는 제공되지 않는것 같은데 혹시 이 이상의 크기는 어떻게 해야할까요?

2022-08-24 22:26 UTC, jimin9038 commented on frontend/src/common/components/Organism/LogInModal.vue
> +  <Modal v-if="props.visible" class="text-green h-[537px] w-[360px]">
> > 그리고 모든 모달 크기가 피그마에 맞춰서 작성된 것 같은데, 피그마 크기는 무시하고 최대한 tailwind css에 클래스로 제공하고 있는 크기를 사용하고, 없다면 지정해주는 방식으로 가면 좋을 것 같아요! 크기는 4px 을 단위로 하는게 좋을 것 같습니다 :)
> 
> 공식문서를 확인해보면 tailwindcss 에서는 w-96 h-96 이상의 크기는 제공되지 않는것 같은데 혹시 이 이상의 크기는 어떻게 해야할까요?

https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values
Arbitrary value 사용하시면 될 것 같습니다.

2022-08-25 14:03 UTC, SOLBI1028 requested changes

2022-08-26 02:15 UTC, SOLBI1028 commented
그리고 [commit convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#-commit-convention-%EF%B8%8F)을 맞춰주시면 좋을 것 같습니다!!

2022-08-26 09:44 UTC, djc06048 commented
> 그리고 [commit convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#-commit-convention-%EF%B8%8F)을 맞춰주시면 좋을 것 같습니다!!

엇 넵 ㅠㅠ 소문자 영문인데 한글로 작성했네요🥲 
다음부터 유의하겠슴다!

2022-08-26 09:50 UTC, djc06048 commented on frontend/src/common/components/Atom/InputItem.vue
> +  notice?: boolean
그게 더 좋을것같네요!! 반영해서 다시 커밋할게욤

2022-08-26 14:33 UTC, dotoleeoak commented
Modal component는 수정할 부분이 좀 있는 것 같아서 따로 PR 올리겠습니다!

2022-09-03 11:36 UTC, dotoleeoak commented
> Modal component는 수정할 부분이 좀 있는 것 같아서 따로 PR 올리겠습니다!

이렇게 하려니까 commit history 관리하기가 애매해져서 그냥 이 PR에서 작업할게요~

2022-09-17 14:32 UTC, dotoleeoak approved these changes

2022-09-18 06:30 UTC, jimin9038 commented on frontend/src/common/components/Atom/Button.vue
> +      ' border border-current bg-transparent'
혹시 여기 의도한 대로 작동하는 게 맞나요? pressed 상태인데 bg-transparent가 적용되어서 약간 이상한 것 같아요~

2022-09-18 10:25 UTC, dotoleeoak commented on frontend/src/common/components/Atom/Button.vue
> +      ' border border-current bg-transparent'
수정했습니다~!

2022-09-19 10:09 UTC, dotoleeoak commented
@pinecone28 댓글 달아주신 것들 전부 반영 한 것 같아요. 리뷰 부탁드립니다!!

2022-09-21 11:59 UTC, pinecone28 approved these changes

2022-09-21 12:03 UTC, merged