feat(fe): add problem-list page
skkuding/next pull request #202
Opened 2022-08-16 11:25 UTC by hbsongk

### Description

problem-list page 구현했습니다!

* Switch 컴포넌트 수정#108 
(Switch 컴포넌트 on/off에 따른 반응형 데이터를 받아오고자, 'switchdata' emit을 추가하여 sendSwitchData 메소드를 통해반응형 data를 부모컴포넌트에 전달하였습니다.

* ProgressCard  컴포넌트 수정#123 
ProgressCard를 눌렀을시 contest url로 이동하게 하기 위한 'card-clicked' emit 추가

* Footer 컴포넌트 수정 X commit
(Footer 컴포넌트 fixed bottom 0을 제거하였는데, eslint/prettier 오류가 떠서 아직 commit은 하지 못했습니다. 감안하고 봐주시면 감사하겠습니닷 :D ) #106

* Tags switch on&off에 따른 paginationtable 두가지 양상 구현

일반형
![1](https://user-images.githubusercontent.com/68498323/184849186-fe331cb5-50a2-4ec8-a4a4-1d16ae7ef040.png)

반응형
![2](https://user-images.githubusercontent.com/68498323/184849199-6eb4230a-600a-422e-b6f0-ba421babb092.png)

### Required component

Header(#126) * 1
Footer(#106) * 1 
PageSubtitle(#92) * 2
Pagination(#70) * 1
SearchBar(#71) * 2
PaginationTable(#72) * 1
ProgressCardComponent(#123) * ?
BoxTitle(#158) * 1
Switch(#108) * 1

### Additional context

- More 버튼 관련해서 해결해야할 문제들이 있습니다. More Button을 어떻게 구현할까 하다 실재적으로 화면에 **보여지는** 요소들을 늘려주면 되지 않을까 싶어 slice(0,2) slice(0,4)와 같이 computed를 통해 제한한 배열을 v-for문에 넣어주었습니다.

계속 smallScreen일때 2,4,6,8
계속 bigScreen일때 4,8
로 늘어나게 하는건 구현가능하였으나

화면이 smallScreen에소 bigScreen으로 커졌을때 혹은 그 역을
**반응형**으로 (ex: 2개 -> 4개) 구현하는 것에 실패하였습니다.
어떻게 해결해야할까요??

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2022-08-17 14:19 UTC, goo314 commented on frontend/src/common/components/Molecule/Switch.vue
> +      @change="sendSwitchData()"
아 @change네요..! 수정해주세요 😅

2022-08-22 14:30 UTC, jimin9038 reviewed
모바일 배려를 위해 css 속성 조금만 추가해주시면 좋을 것 같아요~!

2022-08-22 14:30 UTC, jimin9038 commented on frontend/src/problem/pages/index.vue
> +  <div class="mx-40 mb-28">
width 지정 후 mx-auto가 모바일 배려에 좋을 것 같아요~ #193이 먼저 머지될지는 잘 모르겠는데 header나 footer 같은 공통 부분은 App.vue에서 작성하는 게 좋을 것 같습니당

2022-08-22 14:30 UTC, jimin9038 commented on frontend/src/problem/pages/index.vue
> +    <PaginationTable
여기에 overflow-x scroll 만 추가해도 깔끔해질 것 같아요~

2022-08-23 07:25 UTC, hbsongk commented on frontend/src/problem/pages/index.vue
> +    <PaginationTable
> 여기에 overflow-x scroll 만 추가해도 깔끔해질 것 같아요~

지민님!!군대에서도 이렇게 코드리뷰 남겨주셔서 감사합니다ㅜㅜ 
찬찬히 코드 확인해보고 수정하겠습니다!!! 앞으로도 많이 리뷰해주세욧 :)
혹시 질문사항 생기면 답글 남기겠습니다!!

2022-08-23 14:21 UTC, hbsongk commented on frontend/src/problem/pages/index.vue
> +      :items="problemList"
오오 감사합니다! Pagination 자체적으로 가지고 있는 기능들을 잘 살펴보지 못했던게 큰 것 같네요.
근데 혹시 fields를 ref로 따로 정의하지 않고, 애초에 fields 자체에 { key: 'tag'} 값이 있는걸 default로 하되, 
- switch가 on으로 바뀌는 경우 fields
- switch가 off으로 바뀌는 경우 fields.slice(0, -1)로 정의하는건 어떤가요??

2022-08-23 15:07 UTC, hbsongk commented on frontend/src/problem/pages/index.vue
> +      :items="problemList"
> 페이지네이션 테이블에서 problemList, problemListWithoutTag로 나누지 않고 field 내용만 바꿔주면 테이블 요소가 바껴요~!
> 
> fields를 ref로 정의한 후 switch를 누를때마다 fields를 업데이트하는 코드를 만드는게 더 간단할 것 같아요 😝
> 
> * switch가 on으로 바뀌는 경우 fields에 { key: 'tag' } 추가
> * switch가 off으로 바뀌는 경우 fields의 마지막 요소 제거

오오 감사합니다! Pagination 자체적으로 가지고 있는 기능들을 잘 살펴보지 못했던게 큰 것 같네요.
근데 혹시 fields를 ref로 따로 정의하지 않고, 애초에 fields 자체에 { key: 'tag'} 값이 있는걸 default로 하되,

switch가 on으로 바뀌는 경우 fields
switch가 off으로 바뀌는 경우 fields.slice(0, -1)로 정의하는건 어떤가요??

2022-08-25 12:01 UTC, SOLBI1028 commented
story 실행이 안돼서 main 브랜치 머지했습니다~!

2022-09-03 06:48 UTC, dotoleeoak requested changes

2022-09-03 06:48 UTC, dotoleeoak commented on frontend/src/problem/pages/index.vue
> +          @update:model-value="connectSwitchData"
제가 `Switch` component에서 `model-value` prop을 정의한 이유는 `v-model`을 사용하기 위해서입니다~!
제가 Histoire에 예시 적어뒀습니다. (예: `<Switch v-model="data" />`)
이 부분도 `:model-value`랑 `@update:model-value` props 대신 `v-model` 하나로 대체할 수 있어요.

참고: https://vuejs.org/guide/components/events.html#usage-with-v-model

```vue
<Switch
  label="Tags"
  v-model="isSwitchOn"
/>
```

2022-09-03 06:48 UTC, dotoleeoak commented on frontend/src/problem/pages/index.vue
> +}
https://github.com/skkuding/next/pull/193#discussion_r960686046
이 댓글 참고해주세요~

2022-09-03 06:48 UTC, dotoleeoak commented on frontend/src/problem/pages/index.vue
> +}
라인 207 ~ 231 부분을 조금 더 직관적으로 구현할 수 있을 것 같아요.
표시할 item 개수를 `ref`로 저장하고, more 버튼 클릭 시에는 `window.innerWidth`에 따라 item에 값을 더하는 거 어떨까요?

2022-09-03 06:48 UTC, dotoleeoak commented on frontend/src/problem/pages/index.vue
> +}
저번에도 언급했지만 이 부분은 API 연결하면서 다시 고민해야될 부분이라 지금은 크게 신경 안쓰고 간단하게 구현해도 될 것 같아요.

2022-09-03 14:21 UTC, goo314 commented on frontend/src/problem/pages/index.vue
> +      :items="problemList"
제가 구현한 부분 참고하시면 될 것 같아요~! 😉 #193

2022-09-04 05:24 UTC, goo314 commented on frontend/src/problem/pages/index.vue
> +    <PaginationTable
pagination table의 반응형 부분은 #196 브랜치에서 수정하고 있습니다 빨리 완성시킬게요🥲
problem list 페이지에서는 table, progress-card 외에 반응형이 따로 필요 없는 것 같아 일단 놔뒀습니다

2022-09-04 05:25 UTC, goo314 commented on frontend/src/problem/pages/index.vue
> +          @update:model-value="connectSwitchData"
#193 브랜치에서 사용했던 대로 v-model로 showTags를 연결시켜 computed 속성으로 값이 바뀔때마다 fields를 변환시키는 코드 추가해뒀습니다~!

2022-09-04 05:25 UTC, goo314 commented on frontend/src/problem/pages/index.vue
> +}
수정했습니다 🤩

2022-09-04 05:27 UTC, goo314 commented on frontend/src/problem/pages/index.vue
> +}
처음 화면 새로고침 시 카드 개수는 4개로 통일했고,
More 버튼을 누를때 window.innerWidth 값에 따라 카드 개수를 더하는 방식을 사용했습니다 
추가적으로 전체 카드가 보이면 More버튼은 지워지게 해뒀어요 🤓

2022-09-04 05:29 UTC, goo314 commented
언급해주신 Comment들 전부 수정했고 추가적으로
- Button의 색이 white일때 글씨 색깔을 gray-dark로 변경했어요. 너무 연해서 잘 안보이더라구요.
- ProgressCard의 width, margin값은 상위 컴포넌트에서 정하는 것으로 수정했습니다. width보다는 grid, margin보다는 gap을 많이 쓸 것 같더라구요.

😊😊

2022-09-04 06:38 UTC, dotoleeoak approved these changes

2022-09-04 06:39 UTC, goo314 approved these changes

2022-09-04 07:25 UTC, merged