142 workbook crud
skkuding/next pull request #204
Opened 2022-08-18 08:49 UTC by SH9480P

### Description

Workbook 자체를 생성, 조회, 수정, 삭제하는 api입니다.

**User**
- [GET] group/:groupId/workbook 
group의 visible 필드가 true인 workbook을 모두 조회합니다.
- [GET] group/:groupId/workbook/:workbookId 
visible 필드가 true인 workbook을 하나 조회합니다.

**Group Manager**
- [GET] admin/group/:groupId/workbook 
group의 workbook을 모두 조회합니다.
- [GET] admin/group/:groupId/workbook/:workbookId
 workbook을 하나 조회합니다.
- [POST] admin/group/:groupId/workbook
 workbook을 하나 생성합니다.
- [PUT] admin/group/:groupId/workbook/:workbookId
  workbook을 하나 수정합니다.
- [DELETE] admin/group/:groupId/workbook/:workbookId
 workbook을 하나 삭제합니다.

### Additional context

- public group도 group이므로 public controller를 따로 두지 않았습니다. ex) group/1이 public을 의미
- group/:groupId/workbook 엔드포인트로 가는 요청은 RoleGuard와 GroupMemberGuard를 거칩니다. 따라서 해당 요청은 group에 소속된 사용자만 요청할 수 있습니다.
- admin/group/:groupId/workbook 엔드포인트로 가는 요청은 RoleGuard와 GroupManagerGuard를 거칩니다. 따라서 해당 요청은 group에서 group_manager 이상의 권한을 가진 사용자만 요청할 수 있습니다.
- workbook 수정 API는 PUT 메서드에 해당하므로 API를 호출할 때 FE에서 모든 필드를 전부 채워주어야 합니다.

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-08-19 10:34 UTC, SH9480P commented
아이고.. JwtAuthGuard를 까먹었네요 ㅜㅜ 수정하겠습니다

2022-12-28 06:51 UTC, aintbe requested changes

2022-12-28 06:51 UTC, aintbe commented on backend/src/workbook/workbook-admin.controller.ts
> +        throw new NotFoundException('Cannot find requested workbooks')
요기도 error.message로 수정해주세요!

2022-12-28 06:51 UTC, aintbe commented on backend/src/workbook/workbook-admin.controller.ts
> +        throw new NotFoundException('Cannot find related fields')
create인데 에러 메시지를 find로 알려주는 게 맞을까요?

2022-12-28 06:51 UTC, aintbe commented on backend/src/workbook/workbook-admin.controller.ts
> +        throw new NotFoundException('Cannot find the ID')
workbook does not exist로 메시지 바꿔주세요!

2022-12-28 06:51 UTC, aintbe commented on backend/src/workbook/workbook-admin.controller.ts
> +        throw new NotFoundException('Cannot find the ID')
workbook does not exist로 메시지 바꿔주세요!

2022-12-31 16:48 UTC, SH9480P commented
@aintbe  comment 주신 부분은 전부 수정했습니다. 
### 수정사항
1. workbook을 update하고 delete하는 service layer에서 error가 `PrismaClientKnownRequestError`이고, 추가로 `error.code`가 P2025여야 EntityNotExistException을 던집니다. 에러 코드가 P2025인 경우는 [여기](https://www.prisma.io/docs/reference/api-reference/error-reference#p2025)서 확인 가능합니다.
2. workbook을 create하는 controller에서 `PrismaClientKnownRequestError`인 경우가 불필요하다고 판단, 삭제했습니다. 전달된 `groupId`에 따른 group이 존재하지 않는 경우엔 `GroupLeaderGuard`에서 403 error를 뱉으며 걸러집니다.
3. 에러 메세지를 더 명시적이 되도록 변경했습니다.
### To-Do

- [ ] #300 merge 후 test case 재작성하기

2023-01-11 06:51 UTC, SH9480P commented
### TODO 2023.01.11
1. Group guard를 통과하지 못했을 때 403 error를 뱉는 test case 추가
2. public controller 추가

2023-01-18 08:29 UTC, SH9480P commented
## 수정사항
- UpdateWorkbookDto에 IsNotEmpty class validator를 추가했습니다.
- createWorkbook이 createdById를 req.user.id로 받을 수 있게 변경했습니다.

2023-01-18 14:11 UTC, SH9480P commented
## 수정사항
- UpdateWorkbookDto에 IsNotEmpty class validator를 추가했습니다.
- createWorkbook이 createdById를 req.user.id로 받을 수 있게 변경했습니다.
- workbook 모델의 부분점수 필드를 삭제합니다
- getWorkbooks가 title, description, updateTime만 반환하도록 변경합니다.

2023-01-18 14:45 UTC, goo314 approved these changes
멋져요... 😁

2023-01-19 07:37 UTC, aintbe approved these changes

2023-01-20 06:06 UTC, merged