feat(fe): add Notice List and Detail
skkuding/next pull request #244
Opened 2022-09-18 15:04 UTC by Kohminchae

### Description

Notice list

![image](https://user-images.githubusercontent.com/72334086/190912846-f81484a7-69fe-4569-acf7-99ef2aac9c37.png)

Notice Detail: notice list에서 공지사항 클릭시 나오는 페이지

![image](https://user-images.githubusercontent.com/72334086/190912863-4088e1c5-5225-4e0a-8833-f496820498fe.png)

[Feature] NoticeList 페이지 구현  #228 
[Feature] NoticeDetail 페이지 구현 #229 

### Additional context

notice detail 페이지에서 pagination 의 아이콘, 공지 제목 등의 비율은 pagination table 컴포넌트가 수정되는대로 수정할 예정! 

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-09-19 10:21 UTC, dotoleeoak reviewed
`PaginationTable`에서 dynamic component로 icon 보여주는 게 좋네요 👍
`script setup` 부분에 있는 logic들은 composable로 만들면 좀 더 코드 정리가 잘 될 것 같은데 어떨까요?
`notice/composables/notice.ts`처럼 파일 만들고, 여기에 type, interface, 함수들을 정의하고 import해오는거죠.

참고하기 좋은 composable 예시: https://gist.github.com/yyx990803/8854f8f6a97631576c14b63c8acd8f2e

2023-01-06 15:20 UTC, goo314 commented
> 코드 리뷰 남기려고 했는데 양이 많을 것 같아서 직접 수정했습니다 😃 
> 혹시 작업중이거나 생각해둔 코드 스타일과 다르다면 정말 미안... 🤭 

1. notice list, detail 페이지에서 padding, margin 등 자잘한 style 수정했습니다.
  notice detail 페이지 : 공지사항 제목을 PageSubtitle 컴포넌트 사용
  우측 상단 Bar 아이콘이 화면이 작아짐에 따라 header의 메뉴바와 혼동될 가능성이 있다고 생각해 반응성 스타일을 지웠어요!

2. composables의 `useNotice` 수정했습니다.
  notice list 페이지의 전체 공지사항 목록을 나타내는 `notice`,
  notice detail 페이지에서 현재 공지사항 정보를 나타내는 `currentNotice`,
  notice detail 페이지에서 이전, 이후 공지사항 목록을 나타내는 `adjacentNotice`
  값만을 남겼고, 이외 method로는 `goDetail`과 `getNotice` 만을 남겼습니다.
  이외 pagination-table에서 사용되는 함수는 api연결할때 작성하면 좋을 것 같아 전부 지우고 TODO 남겨놨습니다! 


질문이 있는데 🤔 notice detail 페이지에서는 헤더의 Notice 색상이 active 되지 않더라구요. notice detail 페이지도 active 색상으로 바뀌는 게 사용자 입장에서 볼때 더 나을까요?

<img width="800" alt="image" src="https://user-images.githubusercontent.com/62930375/211039499-fd0057ab-9ae5-46ca-b711-9d1972fbecda.png">

2023-01-07 05:09 UTC, dotoleeoak requested changes

2023-01-07 05:09 UTC, dotoleeoak commented on frontend/src/user/notice/composables/notice.ts
> +export interface Field {
이 부분은 notice와 관련된 interface라기보단 `PaginationTable`이랑 관련된 거라서 다른 곳에서 정의하는 게 좋을 것 같네요!

2023-01-07 05:49 UTC, dotoleeoak commented
> 질문이 있는데 🤔 notice detail 페이지에서는 헤더의 Notice 색상이 active 되지 않더라구요. notice detail 페이지도 active 색상으로 바뀌는 게 사용자 입장에서 볼때 더 나을까요?

@goo314 넵 디테일 좋네요~!

2023-01-08 12:30 UTC, goo314 commented on frontend/src/user/notice/composables/notice.ts
> +export interface Field {
해당부분 notice-detail 페이지로 이동시켰습니다! 😁

2023-01-08 14:07 UTC, goo314 commented
> > 질문이 있는데 🤔 notice detail 페이지에서는 헤더의 Notice 색상이 active 되지 않더라구요. notice detail 페이지도 active 색상으로 바뀌는 게 사용자 입장에서 볼때 더 나을까요?
> 
> @goo314 넵 디테일 좋네요~!

@dotoleeoak 
notice detail 페이지(/notice/:id)에 대해서도 active-class를 적용하고 싶은데 페이지 기반 라우팅을 살펴보니 /notice 와 해당 페이지 url이 서로 다른 route로 인식되더라구요.(parent-child 관계가 아니네요) router-link의 props인 `active-class` 가 아닌 따로 class를 정의하는 방법 밖에 못 찾았는데 혹시 다른 방법이 있을까요? 

'router-link-active' not being applied on nested routes : https://github.com/vuejs/router/issues/984
https://laracasts.com/discuss/channels/vue/vue-router-active-link-only-showing-on-users-and-not-on-usersshow1

2023-01-08 20:11 UTC, dotoleeoak commented
@goo314 찾아봤는데 Vue 3(Vue Router 4)부터 동작이 바뀌어서 아래처럼 nested route일 때 동작하는데, vite-plugin-pages에서 생성하는 route를 보니까 아예 별도의 route로 생성되더라고요. 지금 상태로는 따로 route를 정의하는 게 아닌 이상 일단 별도의 class를 쓰는 게 최선일 거 같네요!

```ts
const routes = [
  {
    path: '/parent/:id',
    children: [
      // empty child
      { path: '' },
      // child with id
      { path: 'child/:id' },
      { path: 'child-second/:id' }
    ]
  }
]
```

참고: https://stackoverflow.com/questions/72620686/show-nested-url-as-active-in-vue-router-when-not-a-child-view

2023-01-10 13:47 UTC, goo314 commented
> @goo314 찾아봤는데 Vue 3(Vue Router 4)부터 동작이 바뀌어서 아래처럼 nested route일 때 동작하는데, vite-plugin-pages에서 생성하는 route를 보니까 아예 별도의 route로 생성되더라고요. 지금 상태로는 따로 route를 정의하는 게 아닌 이상 일단 별도의 class를 쓰는 게 최선일 거 같네요!

https://github.com/hannoeru/vite-plugin-pages#nested-routes
vite-plugin-pages도 nested route를 생성하는데
우리 프로젝트 폴더 구성이 달라서 & vite config 파일에 page-dir을 직접 설정해줘서 
별도의 route로 생성되더라구요. 😭

```typescript
// vite.config.ts
  pages({
      pagesDir: [
        { dir: 'src/user/notice/pages', baseRoute: 'notice' }
       ...
      ]
    })
```

nested route를 생성하는 방향으로 폴더 구조를 바꾸게 되면 
```
user/pages
├─ notice/
│   ├─[id].vue
│   └─ index.vue
├─ notice.vue
...
```
엄청 큰 변화가 있을 것 같아 Kohminchae 가 active 판단하는 함수를 넣어줬어요.
단점은 매 `router-link` 태그마다 함수를 써야 된다는 점....

2023-01-17 07:00 UTC, goo314 approved these changes

2023-01-17 08:02 UTC, dotoleeoak approved these changes

2023-01-17 08:12 UTC, merged