feat(fe): add problem header
skkuding/next pull request #249
Opened 2022-09-22 07:12 UTC by djc06048

### Description
![image](https://user-images.githubusercontent.com/62535887/191681396-fd943f2a-dd07-4d14-9346-0f039bff056e.png)

problem페이지에 들어갈 헤더 입니다.

close #238

2022-09-24 10:11 UTC, dotoleeoak requested changes
Rebase하면서 기존 내용이랑 조금 바뀐 게 있을 수 있어서 확인 부탁드릴게요!
\+ 로고 색상 수정해뒀어요

2022-09-24 10:11 UTC, dotoleeoak commented on frontend/src/admin/pages/index.vue
> +</template>
이 파일은 이 PR이 아니라 다른 곳에서 commit한 것 같은데 잘못 올라온걸까요?
의도한 거 아니면 지워두겠습니다!

2022-12-30 05:26 UTC, goo314 commented on frontend/src/problem/components/Header.vue
> +            color="white"
PaginationTable에서 #246 해당 부분 구현해두었습니다!

2023-01-04 14:56 UTC, dotoleeoak commented on frontend/src/problem/components/Header.vue
> +          <SymbolLogo class="m-4 h-10 w-10 fill-white" />
`m-4` class 때문에 로고 왼쪽에 margin이 생겨서 헤더 전체적으로 왼쪽이랑 오른쪽(user icon) 여백이 다른데, 통일해주는 게 좋을 것 같아요!

2023-01-04 15:23 UTC, dotoleeoak requested changes

2023-01-04 15:23 UTC, dotoleeoak commented on frontend/src/problem/components/Header.vue
> +          </p>
Figma 디자인 보면 > 모양이 따로 아이콘으로 되어있는데, 이 부분 반영 부탁드릴게요! (색깔도 부탁드려요)

![image](https://user-images.githubusercontent.com/19747913/210585021-ae5b8f85-871b-4914-82cd-434d7b5d739c.png)

2023-01-04 15:23 UTC, dotoleeoak commented on frontend/src/problem/components/Header.vue
> +        <div v-if="auth" class="hidden md:inline-block">
홈 화면 헤더에서는 햄버거 메뉴에서 로그인/회원 가입 버튼을 보여줘서 모바일 환경(md 이하)에서 버튼을 숨겼는데, 여기는 그렇게 안해도 괜찮을 것 같은데 어떤가요? 대신 왼쪽의 제목 부분 때문에 공간이 부족할 수 있을텐데, 제목을 다른 방식으로 보이는 게 좋을 것 같아요.

![image](https://user-images.githubusercontent.com/19747913/210586303-7baecd65-d07e-4a24-a645-ffe7b0fba052.png)

2023-01-04 15:23 UTC, dotoleeoak commented on frontend/src/problem/components/Header.vue
> +                class="text-text-title ml-[8.5rem] text-xl hover:opacity-60 active:opacity-40"
Figma에는 유저 아이콘이 흰색이던데 혹시 일부러 다른 색으로 했을까요?

2023-01-04 15:23 UTC, dotoleeoak commented on frontend/src/problem/components/Header.vue
> +              <ListItem @click="auth = false">Log Out</ListItem>
`ListItem` import 확인 부탁드려요!

2023-01-06 06:24 UTC, dotoleeoak approved these changes
수고하셨습니다!

2023-01-10 07:40 UTC, merged