add: problem navigator
skkuding/next pull request #256
Opened 2022-09-28 00:20 UTC by st42597

### Description

<img width="1119" alt="스크린샷 2022-09-28 오전 9 17 39" src="https://user-images.githubusercontent.com/67233988/192659632-21ea5e4a-5e43-48cd-bcf3-a58378385607.png">
problem 페이지의 navigator 구현

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-09-28 01:58 UTC, dotoleeoak requested changes
`Button` component가 main branch에 좀 변경사항이 있어서 main branch merge한 다음 확인 부탁드릴게요!

2022-09-28 01:58 UTC, dotoleeoak commented on frontend/src/problem/components/Navigator.vue
> +          <ListItem>습격자 초라기</ListItem>
`ListItem`이 import가 안 된 것 같아요~?

2022-09-28 01:58 UTC, dotoleeoak commented on frontend/src/problem/components/Navigator.vue
> +import IconRefresh from '~icons/ep/refresh-right'
사소한거긴 한데, 가능하면 font awesome iconset 쓰는 게 전반적인 look & feel이 비슷해져서 좋을 것 같아요...!

```ts
import IconRefresh from '~icons/fa6-solid/arrows-rotate'
```

2022-09-28 01:58 UTC, dotoleeoak commented on frontend/src/problem/components/Navigator.vue
> +  <div class="flex h-14 w-full flex-row items-center bg-slate-700 px-6">
Context를 좀 더 살리기 위해서 `div` 대신 `nav` 쓰는 거 어떨까요?
(관련해서 "Semantic HTML" 검색해보세요)

2022-09-29 06:26 UTC, st42597 commented on frontend/src/problem/components/Navigator.vue
> +import IconRefresh from '~icons/ep/refresh-right'
font awesome에서 refresh 아이콘 찾아봤는데 두꺼운거밖에 없더라고요 ㅜㅜ

2022-09-29 13:47 UTC, dotoleeoak commented on frontend/src/problem/components/Navigator.vue
> +import IconRefresh from '~icons/ep/refresh-right'
음... 좀 아쉽네요 그럼 일단 이대로 둘게요

2022-12-29 07:20 UTC, dotoleeoak approved these changes

2022-12-29 07:30 UTC, merged