247 problem clarification
skkuding/next pull request #276
Opened 2022-11-03 03:08 UTC by hbsongk

### Description

problem에 관한 공지사항을 볼 수 있는 clarification button을 추가합니다.

1. clarification button 클릭 시, 공지사항 open. 다시 한번 클릭 시 close.
2. clarification button을 drag&drop 하여 원하는 위치로 이동할 수 있습니다.
3. 가장 최신 공지사항에 한하여 확성기 이모티콘을 빨간색으로 추가했습니다.
4. screen width에 따라 공지사항이 interactive하게 보여집니다.

![description](https://user-images.githubusercontent.com/68498323/199638889-dfcd7d36-1039-46b1-a677-ce50bab61bde.gif)

### Additional context

clarification button의 위치에 따른 2가지 문제 상황이 발생했는데 
더 이상 PR을 늦추면 진행이 더뎌질 것 같아 PR 올려봅니다.

1. button screen 밖을 빠져나가는 상황
- @pointerup event를 통해 button의 위치가 0보다 작아지거나, 
    screen-54(button의 width)보다 커졌을 때를 기준으로,
    screen 밖으로 빠져나가지 못하게 조건을 걸어 놓았는데,
    **@pointerup**이라는 event를 기준으로 하기 때문에,
    pointer가 먼저 screen밖으로 빠져나갈 시, 해당 event가
    호출이 되지 않는 상황이 발생했습니다.
    
2. screen이 resize 되는 상황
- 위에서 언급한 방식과 동일한 방식으로 조건문을 걸어 처리하려고 하였으나,
   screen을 resize했을 때 trigger 되는 event를 찾지 못해 처리를 못하였습니다.
   1.

도와주세욧! 
    

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2022-11-03 05:32 UTC, goo314 commented
pr 제목 바꿨어요 ~~
problem 폴더 지워주고 usr/problem 폴더만 남겨주세요 :)

2022-11-10 14:53 UTC, hbsongk commented
> pr 제목 바꿨어요 ~~ problem 폴더 지워주고 user/problem 폴더만 남겨주세요 :)

넴 수정 완료했습니다~~ 얍얍

2023-01-03 07:38 UTC, goo314 requested changes

2023-01-03 07:38 UTC, goo314 commented on frontend/src/user/problem/components/Clarification.vue
> +    class="bg-white-light border-gray fixed m-auto h-96 w-1/2 overflow-auto rounded-md border border-solid py-2 px-6"
`bg-white-light` 는 없는 클래스명이라 투명하게 보이는 것 같은데 `bg-white`로 고치는 것은 어떨까요?
그리고 해당 부분은 z-index 값을 줘서 페이지 위로 올리면 좋을 것 같아요!

2023-01-05 06:43 UTC, hbsongk commented on frontend/src/user/problem/components/Clarification.vue
> +    class="bg-white-light border-gray fixed m-auto h-96 w-1/2 overflow-auto rounded-md border border-solid py-2 px-6"
@goo314 수정완료했습니다~

2023-01-05 07:06 UTC, goo314 approved these changes

2023-01-05 07:06 UTC, merged