chore(fe): add padding to layout
skkuding/next pull request #304
Opened 2022-12-29 07:09 UTC by goo314

### Description

- admin layout
  - padding 값 추가
  - Sidebar prop boolean -> string 수정
- directory 변경
  - manager -> admin 으로 이름 변경

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-12-29 10:38 UTC, dotoleeoak commented on frontend/src/common/components/Organism/Sidebar.vue
> +        { to: 'home', name: props.group.toUpperCase(), icon: IconBiHouse },
path 이름이 root(`/`)가 맞지 않나요??

2022-12-30 05:41 UTC, goo314 commented on frontend/src/common/components/Organism/Sidebar.vue
> +        { to: 'home', name: props.group.toUpperCase(), icon: IconBiHouse },
admin main 페이지가 `/`이고

<img width="300" alt="image" src="https://user-images.githubusercontent.com/62930375/210038085-d5722cdc-0a68-4a11-8c6c-cacb6d034b8e.png">

해당 코드가 가야할 곳은 group의 main 페이지 위치 `:id` 인데...

<img width="300" alt="image" src="https://user-images.githubusercontent.com/62930375/210038094-8d500452-89a6-49a2-ab6a-bb830997cf50.png">

이부분은 나중에 API 연동할때 수정하려고 남겨 뒀던 것 같아요! 
사이드바에 필요한 정보가 group 이름과 id인데
- meta값으로 id와 그룹 이름을 넘겨주는 형식으로 바꾸거나 
- 아니면 layout meta값으로 id값만 넘겨주고 그걸로 그룹 이름이랑 라우팅을 결정하거나
해야될 것 같아요!! 음.... 바꿔서 커밋 올릴까요??

2022-12-30 06:05 UTC, goo314 commented
옴마나 admin이 아니라 manager이었네요!!! 으악 혼동을 드려 죄송합니다 😱
이 PR 보다 PagainationTable이 먼저 merge되면 close 시킬게요

2023-01-07 05:48 UTC, dotoleeoak commented
> 이 PR 보다 https://github.com/skkuding/next/pull/285 이 먼저 merge되면 close 시킬게요

@goo314 혹시 아직 유효한가요?

2023-01-07 05:50 UTC, goo314 commented
> > 이 PR 보다 https://github.com/skkuding/next/pull/285 이 먼저 merge되면 close 시킬게요
> 
> @goo314 혹시 아직 유효한가요?

생각보다 수정한게 많아져서 아니요😂

2023-01-07 07:53 UTC, dotoleeoak commented on frontend/src/common/components/Organism/Sidebar.vue
> +        { to: 'home', name: props.group.toUpperCase(), icon: IconBiHouse },
바꾸거나 아니면 TODO comment 남겨주세요!
따로 기록한 거 없으면 나중에 혼동이 있을 거 같아요

2023-01-07 07:59 UTC, dotoleeoak requested changes
Story vkdlf

2023-01-07 07:59 UTC, dotoleeoak commented on frontend/src/common/components/Organism/Sidebar.story.vue
>  </template>
Props 변경돼서 story 파일 build가 깨지는데 확인 부탁드릴게요!

2023-01-08 16:22 UTC, goo314 commented on frontend/src/common/components/Organism/Sidebar.vue
> +        { to: 'home', name: props.group.toUpperCase(), icon: IconBiHouse },
named route를 이용해 해당 부분 수정했습니다 🤔
type checking 때문에 group 초기값이 `id=-1`로 설정해서 코드가 지저분한데
이부분 곧 수정해서 커밋 올릴게요!! group type을 전체적으로 다시 수정할 것 같아요 잠시만요 ✋

2023-01-08 16:27 UTC, goo314 commented on frontend/src/common/components/Organism/Sidebar.story.vue
>  </template>
해당부분 수정해서 build test 통과되도록 했습니다. 근데 group type 바꿀 예정이라 확정은 아니에요! ✋

2023-01-21 10:02 UTC, closed without merging