feat(fe): use tailwindcss
skkuding/next pull request #33
Opened 2022-04-03 06:41 UTC by jimin9038

### Description

CSS Utiility framework로 tailwindcss 를 사용합니다. 
기본 Config에서 우리 프로젝트에서 메인으로 사용하는 컬러들을 기준으로 [Tint & Shade Generator](https://maketintsandshades.com/#24272D)를 이용하여 설정하였으며, 폰트의 경우 sans는 기본으로 Manrope와 Noto Sans KR(한국어 fallback), mono는 JetBrains Mono, admin은 Noto Sans KR을 이용하도록 설정했습니다. 구글 웹 폰트 API를 이용하여 폰트 파일을 다운 받습니다. 

### Additional context

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-04-03 07:18 UTC, dotoleeoak requested changes

2022-04-03 07:18 UTC, dotoleeoak commented on frontend/index.html
> +    />
사용할 font weight도 정의하는게 좋겠네요. 기본적으로는 normal weight만 불러올 거에요.

Google Font 문서: https://developers.google.com/fonts/docs/css2
참고: https://github.com/skkuding/skku-coding-platform/blob/dev/vue-3/frontend-new/index.html

2022-04-03 07:18 UTC, dotoleeoak commented on frontend/tailwind.config.js
> +        admin: ['Noto Sans KR', ...defaultTheme.fontFamily.sans],
admin은 아직 어떻게 구현될 지 안 정해졌으니까 이 부분은 나중에 필요해지면 추가하는 게 좋을 것 같아요.
(같이 bundle될지, tailwind를 쓸지 등)

2022-04-03 07:18 UTC, dotoleeoak commented on frontend/tailwind.config.js
> +        700: '#173747', // Basis (Problem.vue)
웬만하면 기본으로 정의된 색상을 쓰는 게 좋아보이는데, 다른 색상을 쓰는 이유가 있나요?
만약 꼭 따로 써야한다면 slate, neutral 같은 기본 색상은 그냥 두고, 별도 키워드로 색상을 추가하는 게 나을 것 같아요.

2022-04-03 07:46 UTC, jimin9038 commented on frontend/tailwind.config.js
> +        700: '#173747', // Basis (Problem.vue)
extends로 기존 색상에 추가해서 쓰는 방법도 있기는 한데, 그것보다는 저희가 쓸 색상 계열과 Shade를 미리 정해놓고 쓰는게 더 낫겠다는 생각이 들었어요. 사용하는 색들을 학교 컬러들과 비슷하게 가져가는 게 사용자에게 학교 플랫폼을 사용하고 있다는 느낌을 줄 수 있을 것 같다는 게 첫번째 이유고, tailwindcss에서 제공하는 색상 계열이 너무 많아서 관리가 어려울까봐가 두번째 이유입니다.
같은 색의 여러 Shade를 정해놓고 쓰면 계열 자체는 같기 때문에 상황에 따라 다르게 쓰기 좋고, 나중에 다크 모드를 구성할 때도 설정하기 쉽지 않을까 싶어요~
오히려 저는 default color를 없앨까 생각중인데 어떤가요 ?? 🤔

2022-04-03 07:46 UTC, jimin9038 commented on frontend/tailwind.config.js
> +        admin: ['Noto Sans KR', ...defaultTheme.fontFamily.sans],
좋습니당

2022-04-03 07:46 UTC, jimin9038 commented on frontend/index.html
> +    />
넵~

2022-04-03 08:04 UTC, dotoleeoak commented on frontend/tailwind.config.js
> +        700: '#173747', // Basis (Problem.vue)
안 쓰는 default color 일부를 없애는 건 어느 정도 공감하는데, tailwind에서 제공하는 것 이외의 색상을 쓰는 건 좀 회의적이네요. 우리 팀에 아직 디자인을 전문으로 하는 팀원이 없어서 임의의 색상을 사용하는 거에 조심스러운데, tailwind에서 제공하는 기본 색상은 저명한 디자이너들이 정해둔 색상들이니까요.

학교 느낌을 내기 위한 색을 넣는다하면 연두색(#8dc63f) 하나로도 충분하다고 생각하는데, 이건 tailwind에서 lime-400이나 lime-500이랑 꽤 비슷해서 이 색상으로 하면 될 것 같아요. 꼭 필요한 경우는 앞서 말한 것처럼 extend해서 쓰고요. 나머지 색상들은 확실한 이유가 있는게 아니면 디자인 팀원을 따로 구하기 전까지는 기본 색상 쓰는 편이 나을 것 같네요.

2022-04-03 11:58 UTC, jimin9038 commented on frontend/tailwind.config.js
> +        700: '#173747', // Basis (Problem.vue)
글쎄요.. 뭐 tailwindcss 색상이 전문가 분들이 했다고는 하지만 기본 색상을 이용해서 맞춰도 약간의 이질감이 있더라구요. 저희가 디자인 하면서 어울린다고 느꼈기 때문에 커스텀된 색을 썼을거라고 생각합니다. 물론 나중에 디자인이나 색상에 대해 잘 아는 분들이 온다면 디자인과 같이 리뉴얼하는 편은 좋습니다. 
red와 neutral은 굳이 커스텀은 안해도 될 것 같아서 이 부분만 날리고, 일단은 이렇게 쓰는 걸로 하죠

2022-04-03 23:30 UTC, dotoleeoak requested changes

2022-04-03 23:30 UTC, dotoleeoak commented on frontend/index.html
> +    />
monospaced 폰트는 normal weight만 있어도 될 거 같아요

2022-04-04 05:01 UTC, dotoleeoak approved these changes

2022-04-04 05:01 UTC, merged