feat(fe): connect contest list api
skkuding/next pull request #336
Opened 2023-01-12 11:52 UTC by hbsongk

### Description

contest list api를 통해 ongoing, incoming, finished contest data를 받아옵니다.

### Additional context

register now Contest를 지웠는데, 필요여부에 대한 논의가 필요합니다.

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2023-01-12 16:16 UTC, goo314 requested changes

2023-01-12 16:16 UTC, goo314 commented on frontend/src/user/contest/pages/index.vue
>      ]"
item의 id와 헷갈려서 그러는데 혹시 이부분 
`id`말고 `status`로 고쳐주실 수 있나요 ??

2023-01-12 16:16 UTC, goo314 commented on frontend/src/user/contest/pages/index.vue
>    if (id === 'ongoing' || id === 'registerNow')
`registerNow` 지워주세요!

2023-01-14 14:20 UTC, goo314 commented
close #314 추가해주세요 ...

2023-01-14 14:35 UTC, goo314 requested changes

2023-01-14 14:35 UTC, goo314 commented on frontend/src/user/contest/pages/index.vue
> -          :description="item.description"
아 피그마 디자인 상으로 description에 해당하는 부분은 `For [group이름]` 이었네요!! 수정 바랍니다 😅

<img width="700" alt="image" src="https://user-images.githubusercontent.com/62930375/212477153-a9818ddd-d031-43b6-a245-11335202da1a.png">

2023-01-15 08:03 UTC, hbsongk commented on frontend/src/user/contest/pages/index.vue
>    if (id === 'ongoing' || id === 'registerNow')
수정 했습니다~

2023-01-15 08:03 UTC, hbsongk commented on frontend/src/user/contest/pages/index.vue
>      ]"
> item의 id와 헷갈려서 그러는데 혹시 이부분 `id`말고 `status`로 고쳐주실 수 있나요 ??

수정했습니다~

2023-01-15 08:04 UTC, hbsongk commented on frontend/src/user/contest/pages/index.vue
>    if (id === 'ongoing' || id === 'registerNow')
> `registerNow` 지워주세요!

수정완료 했습니다!

2023-01-15 08:04 UTC, hbsongk commented
> ### Description
> contest list api를 통해 ongoing, incoming, finished contest data를 받아옵니다.
> 
> ### Additional context
> register now Contest를 지웠는데, 필요여부에 대한 논의가 필요합니다.
> 
> ### Before submitting the PR, please make sure you do the following
> * [x]  Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
> * [x]  Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
> * [x]  Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
> * [x]  Ideally, include relevant tests that fail without this PR but pass with it.



> close #314 추가해주세요 ...

추가했습니다~

2023-01-15 08:06 UTC, hbsongk commented on frontend/src/user/contest/pages/index.vue
> -          :description="item.description"
@goo314 명확하게 이해가 안돼서 그러는데 혹시 :description = "item.group.groupName"으로 description 부분 추가하라는 말씀이신가요?

2023-01-15 09:13 UTC, dotoleeoak commented on frontend/src/user/contest/pages/index.vue
> -          :description="item.description"
`:description="'For ' + item.group.groupName"`로 추가하면 될 것 같아요~!

2023-01-15 12:23 UTC, hbsongk commented on frontend/src/user/contest/pages/index.vue
> -          :description="item.description"
> `:description="'For ' + item.group.groupName"`로 추가하면 될 것 같아요~!

아아 무슨 뜻인지 이제 이해했습니다ㅋㅋㅋ감사합니다~!~!

2023-01-15 12:33 UTC, hbsongk commented on frontend/src/user/contest/pages/index.vue
> -          :description="item.description"
> 아 피그마 디자인 상으로 description에 해당하는 부분은 `For [group이름]` 이었네요!! 수정 바랍니다 😅
> 
> <img alt="image" width="700" src="https://user-images.githubusercontent.com/62930375/212477153-a9818ddd-d031-43b6-a245-11335202da1a.png">

수정 완료 했습니다!

2023-01-16 00:57 UTC, dotoleeoak requested changes

2023-01-16 00:57 UTC, dotoleeoak commented on frontend/src/user/contest/pages/index.vue
>  import { ref } from 'vue'
사소하긴 한데 import 정리 부탁드려요!

```suggestion
import { ref, onMounted } from 'vue'
```

2023-01-17 04:49 UTC, hbsongk commented on frontend/src/user/contest/pages/index.vue
>  import { ref } from 'vue'
@

> 사소하긴 한데 import 정리 부탁드려요!

수정 완료했습니다~

2023-01-17 07:55 UTC, goo314 commented on frontend/src/user/contest/pages/index.vue
>      </div>
요기 v-if 에 `items[status]?.length===0 || showFinished` 넣고 아래 v-else-if 문 안에 내용은 지워도 됩니다!

2023-01-17 08:00 UTC, goo314 commented on frontend/src/user/contest/pages/index.vue
>      </div>
앗 아니요 이렇게 되버리면 finished contest가 있는 경우에도 no contest만 보여서.. 잠시만요!

2023-01-17 08:03 UTC, goo314 commented on frontend/src/user/contest/pages/index.vue
>      </div>
`items[status]?.length === 0 && (status !== 'finished' || showFinished)`

2023-01-17 08:06 UTC, hbsongk commented on frontend/src/user/contest/pages/index.vue
>      </div>
@goo314 수정했습니다~

2023-01-17 08:19 UTC, goo314 approved these changes

2023-01-17 08:22 UTC, dotoleeoak approved these changes
수고하셨습니다!

2023-01-17 08:22 UTC, merged

2023-01-17 08:23 UTC, hbsongk commented
> 수고하셨습니다!

감사합니다 주륵