338 problem header
skkuding/next pull request #339
Opened 2023-01-14 15:24 UTC by st42597

### Description

<img width="1187" alt="스크린샷 2023-01-15 오전 12 22 55" src="https://user-images.githubusercontent.com/67233988/212479506-6ae6883e-7167-4260-b0b0-5347a6899c84.png">
- 디렉토리와 이름 수정
- border과 user icon class로 인한 디자인 오류 수정

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2023-01-16 00:50 UTC, dotoleeoak reviewed
어차피 component가 problem module 내에 있으니까 context 상으로 ProblemHeader인 걸 알 수 있어서 Header.vue로 이름 지어도 괜찮을 것 같은데, 어떤가요?

2023-01-16 18:16 UTC, goo314 requested changes

2023-01-16 18:16 UTC, goo314 commented on frontend/src/user/problem/components/ProblemHeader.vue
> +    class="border-b-gray bg-text-subtitle grid h-14 place-items-center px-8"
여기 border 값을 없앤건가요? 없앴으면 `border-b-gray` 값도 지워주세요!

2023-01-16 18:16 UTC, goo314 commented on frontend/src/user/problem/components/ProblemHeader.vue
> +              <IconUser class="text-xl" color="white" />
여기는 굳이 안바꿔도 white 색상으로 나옵니다! 🤔

2023-01-17 06:28 UTC, st42597 commented
> 어차피 component가 problem module 내에 있으니까 context 상으로 ProblemHeader인 걸 알 수 있어서 Header.vue로 이름 지어도 괜찮을 것 같은데, 어떤가요?

그렇긴한데 story에서 메인 페이지 Header와 problem 페이지의 Header가 이름 충돌이 나서 일단 ProblemHeader로 이름을 변경했어요

- ProblemHeader로 이름을 바꾼다
- 어차피 problem page에서만 사용하는 component기 때문에 story를 제거하고 Problem으로 원래 이름을 사용한다

둘 다 좋아보이는데 어떻게 할까요?

2023-01-17 07:26 UTC, goo314 commented
> 그렇긴한데 story에서 메인 페이지 Header와 problem 페이지의 Header가 이름 충돌이 나서 일단 ProblemHeader로 이름을 변경했어요
> 
> * ProblemHeader로 이름을 바꾼다
> * 어차피 problem page에서만 사용하는 component기 때문에 story를 제거하고 Problem으로 원래 이름을 사용한다
> 
> 둘 다 좋아보이는데 어떻게 할까요?

이름 충돌 나는 것은 #241 hostoire group 분류로 아마 해결할 수 있을거에요.
근데 아직 group 을 어떻게 나눠질지 정한 건 아니라서, 일단 navigator 처럼 story 지우는 것도 나쁘지 않을 것 같아요!

2023-01-17 07:43 UTC, st42597 commented
> 

story지우는 쪽으로 할게요!

2023-01-17 08:00 UTC, st42597 commented on frontend/src/user/problem/components/ProblemHeader.vue
> +              <IconUser class="text-xl" color="white" />
그렇긴한데 별도의 class로 white값을 주는 것보다 Iconify 가이드라인 따르는게 좋아보여서 수정했습니다.

2023-01-19 03:44 UTC, goo314 approved these changes
바뀐게 크게 없는 것 같아서 이대로 진행해도 괜찮을 것 같아요~ 부수적인 부분은 Problem 페이지 하면서 차차 생각해봐요.

2023-01-19 07:50 UTC, merged