chore(be): Add issue template for components
skkuding/next pull request #61
Opened 2022-06-25 12:10 UTC by SOLBI1028

### Description
Frontend에서 component를 개발할 때 사용할 issue template을 작성합니다.
[Example](https://github.com/SOLBI1028/Issue-template/issues/3)

closes #60 

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-06-25 13:27 UTC, goo314 commented
commit부분에 be가 아니라 fe 아닌가요?
이슈 템플릿은 예뻐요 ☺️

2022-06-25 13:54 UTC, goo314 approved these changes

2022-06-25 13:54 UTC, goo314 commented on .github/ISSUE_TEMPLATE/frontend-component-dev.yml
> +      description: 해당 컴포넌트에서 사용할 method에 대해 자세하게 설명해주세요.
Vue3에서 상위 컴포넌트로 전달하는 `emit` attribute도 생겨서 추가하면 좋을 것 같아요 😗

2022-06-25 13:58 UTC, goo314 commented on .github/ISSUE_TEMPLATE/frontend-component-dev.yml
> +      description: 해당 컴포넌트에서 사용할 method에 대해 자세하게 설명해주세요.
없어도 될 것 같기도 해요 😋

2022-06-25 14:01 UTC, SOLBI1028 commented on .github/ISSUE_TEMPLATE/frontend-component-dev.yml
> +      description: 해당 컴포넌트에서 사용할 method에 대해 자세하게 설명해주세요.
`emit`은 이슈 작성단계에서 모두 생각하긴 힘들 것 같아요! 
구현 단계에서 필요 시 적는걸로 해요!~!

2022-06-25 23:38 UTC, dotoleeoak requested changes

2022-06-25 23:38 UTC, dotoleeoak commented on .github/ISSUE_TEMPLATE/frontend-component-dev.yml
> +      label: ☁️ Method
data랑 method는 component 내부에서 쓰일텐데, component를 구현하는 입장 대신 사용하는 입장에서는 이 부분이 abstract되는 게 좋을 거 같아요. 내부적인 구현 사항은 사용하는 입장에서 모르도록 하고 issue에서는 component 외부적인 것만 명시하도록 하는 게 어떨까요? 실제 구현 사항은 issue를 올리는 기획 단계에서는 완전히 정하기 어렵기도 해서요

2022-06-25 23:38 UTC, dotoleeoak commented on .github/ISSUE_TEMPLATE/frontend-component-dev.yml
> +      label: ☁️ Method
전반적으로 issue는 '어떤 기능이 왜 필요한지' 중심으로, pull request는 '어떻게 구현했는지' 중심으로 적으면 flow가 좀 더 깔끔할 거 같아요

2022-06-26 06:05 UTC, SOLBI1028 commented on .github/ISSUE_TEMPLATE/frontend-component-dev.yml
> +      label: ☁️ Method
아 이해했습니다! 그럼 data, method부분은 빼고 커밋 다시 남기도록 할게요

2022-06-26 06:19 UTC, SOLBI1028 commented on .github/ISSUE_TEMPLATE/frontend-component-dev.yml
> +      label: ☁️ Method
props도 비슷한 맥락으로 빼도 될것 같은데, data, props, method 모두 빼는걸로 할까요?

2022-06-26 07:06 UTC, dotoleeoak commented on .github/ISSUE_TEMPLATE/frontend-component-dev.yml
> +      label: ☁️ Method
props는 component 외부로 노출되는 거니까 두는 것도 괜찮을 것 같은데, 구현적인 내용이긴 하니까 원하는대로 해주세요

2022-06-26 07:23 UTC, SOLBI1028 commented on .github/ISSUE_TEMPLATE/frontend-component-dev.yml
> +      label: ☁️ Method
말씀해주신대로 사용적인 측면에서 필요할 것 같아서 props는 남겨두었습니다~!

2022-06-26 07:35 UTC, dotoleeoak approved these changes
좋습니다~

2022-06-26 08:07 UTC, merged