feat: use Vitepress for ducumentation
skkuding/next pull request #65
Opened 2022-06-26 15:44 UTC by SOLBI1028

![image](https://user-images.githubusercontent.com/75013515/175820787-5a63c555-2423-412a-8c64-852f1cb70b7e.png)

### Description
- 문서화를 위해 Vitepress를 이용합니다.
- 초기 page는 index.md로 설정하였고, frontend와 backend 문서의 주제를 구분하기 위해 디렉토리를 따로 생성하였습니다.
- 문서의 틀을 결정하기위해 각 카테고리마다 제목만 작성한 파일을 1개씩 추가하였고, 테스트를 위해 기존에 작성되어 있는 contributing guide를 작성하였습니다. (사진을 참고해주세요)

### 사용방법
1. 문서 작성 후 `docs/.vitepress/config.js` 의 `sidebar`에 추가한 문서의 내용에 해당하는 주제에 문서의 제목과 링크를 추가해 주세요.
   링크의 규칙은 [여기](https://vitepress.vuejs.org/guide/theme-sidebar.html#multiple-sidebars)를 따라주시면 됩니다.
2. 작성한 문서는 `pnpm docs:dev` 명령어를 통해 _localhost:5555/next/_ 에서 미리 확인하실 수 있습니다.
3. 배포된 문서는 해당 PR이 merge된 후 [여기](skkuding.github.io/next/)서 확인하실 수 있습니다.

Close #63 

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-06-27 10:09 UTC, dotoleeoak requested changes

2022-06-27 10:09 UTC, dotoleeoak commented on docs/.vitepress/config.js
> +}
config 파일은 typescript 쓰는 게 나을 것 같아요
option들 자동완성돼서 작성할 때 도움될 거에요

2022-06-27 10:09 UTC, dotoleeoak commented on docs/frontend/Atom/button.md
> +# Button
component 각각에 대한 문서는 나중에 storybook으로 따로 만들고, 이 문서에는 전반적인 코드 구조랑 기능들 설명하는 방향이 좋아보이는데 어떨까요?

2022-06-27 10:09 UTC, dotoleeoak commented on docs/introduction/contributing-guide.md
> +WIP
이 파일은 symbolic link로 대체하는 거 어떨까요?
root에도 contributing guide 파일은 계속 둘테니까, link시켜서 한 번에 한 파일만 수정하게끔이요

2022-06-27 15:14 UTC, SOLBI1028 commented on docs/frontend/Atom/button.md
> +# Button
각 컴포넌트 문서를 storybook으로 따로 빼는건 좋은 것 같아요! 
그러면 이 문서에는 frontend은 모듈별로 각 페이지별 전반적인 코드 구조랑 기능을 설명 하자는 말씀이신 것 같은데 페이지 구성이 감이 잘 안오네요..! 혹시 참고할만한 사이트를 알려주시면 참고해서 구성해보겠습니다!

2022-06-28 10:40 UTC, dotoleeoak commented on docs/frontend/Atom/button.md
> +# Button
frontend 팀의 workflow를 설명할 수도 있고(예를 들면, 기획 -> 디자인(figma) -> 이슈 등록 -> 구현 -> PR), 페이지를 route 기준으로 나눠서 각 페이지의 기능이나 기획 의도 등을 설명할 수도 있고, frontemd의 기술 스택과 라이브러리 등을 설명할 수도 있겠죠? 관련 자료를 찾아보려 했는데 아쉽게도 마땅한 예시가 없긴 하네요...

2022-06-30 07:28 UTC, SOLBI1028 commented on docs/frontend/Atom/button.md
> +# Button
이 부분은 조금 더 고민해보고 수정해서 다시 커밋남기도록 하겠습니다!

2022-07-05 10:49 UTC, SOLBI1028 commented on docs/frontend/Atom/button.md
> +# Button
프론트엔드의 페이지의 기능이나 기획 의도등은 use case로 설명이 가능할 것 같아서 사용자별(user, group admin) use case 페이지를 추가했습니다! 그리고 백엔드와 프론트엔드 구분을 없애고, API 문서나 judge server 등과 같이 필요한 백엔드 페이지는 추후에 작성할때 추가하는 걸로 하면 될 것 같습니다~!

2022-07-15 14:34 UTC, dotoleeoak commented
지금 제가 문서 작성하고 있어서, 작성 끝나면 다시 ready to merge 라벨 걸어둘게요~~

2022-09-11 23:10 UTC, dotoleeoak commented
Cloudflare pages로 배포 해뒀고, domain은 [docs.skkuding.dev](https://docs.skkuding.dev)로 설정해뒀습니다!

2022-11-11 11:13 UTC, dotoleeoak approved these changes

2022-11-11 11:13 UTC, merged