chore(fe): setup base file of frontend
skkuding/next pull request #85
Opened 2022-06-28 11:51 UTC by SOLBI1028

### Description
- vite plugin pages 규칙에 따라 각 모듈 별 base file을 생성하였습니다.
- module : `notice`, `contest`, `problem`, `group`, `home`
- 하나의 요소(contest, group)에 대해 여러개의 detail page가 필요한 경우에는 id를 디렉토리 명으로 하여 하위 page들을 생성하였습니다.
- 공통적인 스타일링을 위해 필요한 색상을 `tailwind.cofig.js`파일에 설정해주었습니다.

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-06-28 13:04 UTC, SOLBI1028 commented
> 하나의 contest, group에 대해 여러 detail page가 필요한 경우가 어떤건지 모르겠어요 😢 매 contest마다 contestID 폴더가 생기는거에요? 비슷한 vue파일이 여러개 생기는거 아니에요? 😱

notice나 problem의 경우에는 notice의 내용을 보여주는 detail page 한개, problem의 경우에는 problem을 풀 수 있는 problem detail page한개가 필요해요. 하지만
contest는 하나의 contest에 대해 top, ranking, problem list, notice page가 필요하고, 
gorup은 하나의 group에 대해 notice, workbook, contest, member page가 필요하겠죠?!

그리고 프론트엔드에서 라우팅 방식으로 vite plugin page을 따르고 있는데, [id]의 형식으로 폴더명 / 파일명을 작성하면 동적으로 라우팅을 할 수 있기 때문에 매 contest/group 마다 폴더가 새로 생기는게 아니에요!
https://www.wenyanet.com/opensource/ko/6117ccb62359cb27c273a19e.html <- 파일 시스템 라우팅 부분을 참고하시면 이해 될거에요.

2022-06-29 01:10 UTC, goo314 commented
> > 하나의 contest, group에 대해 여러 detail page가 필요한 경우가 어떤건지 모르겠어요 😢 매 contest마다 contestID 폴더가 생기는거에요? 비슷한 vue파일이 여러개 생기는거 아니에요? 😱
> 
> notice나 problem의 경우에는 notice의 내용을 보여주는 detail page 한개, problem의 경우에는 problem을 풀 수 있는 problem detail page한개가 필요해요. 하지만 contest는 하나의 contest에 대해 top, ranking, problem list, notice page가 필요하고, group은 하나의 group에 대해 notice, workbook, contest, member page가 필요하겠죠?! 이런 경우를 여러 detail page가 필요하다고 표현했고, 이 페이지들을 하나의 파일에 다 넣을 수는 있겠지만 다 다른 내용을 담고 있기 때문에 분리하는게 더 좋을 것 같아서 분리했어요!
> 
> 그리고 프론트엔드에서 라우팅 방식으로 vite plugin page을 따르고 있는데, [id]의 형식으로 폴더명 / 파일명을 작성하면 동적으로 라우팅을 할 수 있기 때문에 매 contest/group 마다 폴더가 새로 생기는게 아니에요! https://www.wenyanet.com/opensource/ko/6117ccb62359cb27c273a19e.html <- 파일 시스템 라우팅 부분을 참고하시면 이해 될거에요.

아 오늘 아침에 보니까 이해했어요 😆 감쟈합니다 😉

2022-06-29 09:48 UTC, goo314 approved these changes

2022-06-29 11:51 UTC, dotoleeoak requested changes

2022-06-29 11:51 UTC, dotoleeoak commented on frontend/src/common/styles/style.css
> +  --vt-c-indigo: #212529;
style.css에서 맨 위 3줄에 `@tailwind` 부분 제외하고는 전부 기본 boilerplate에 포함되어있던 거라 필요없을 거 같은데, 지우는 거 어떨까요?

2022-06-29 11:51 UTC, dotoleeoak commented on frontend/src/components/Atom/AtomComponent.vue
> +-->
아마 snippet을 미리 작성해두려는 의도였을 거 같은데, `script setup`이랑 `template` 빼고는 지우는 게 좋을 것 같아요.
`<script lang="ts">` 부분은 Vue 3에서 전부 script setup으로 작성 가능하고 가독성도 script setup이 나을 것 같아요.
사실 options API랑 composition API에 대한 논쟁은 아직도 계속 있긴 한데, 일단 적어도 하나의 스타일을 유지하는 게 좋을 것 같고, 제 생각엔 composition API(script setup)이 좀 더 간결해서 좋아보여요.

ESLint rule로 이걸 강제하는 것도 괜찮을 것 같아요
https://eslint.vuejs.org/rules/component-api-style.html

2022-06-29 11:51 UTC, dotoleeoak commented on frontend/src/components/Atom/AtomComponent.vue
> +-->
그리고 `src/component` 폴더를 만들었는데, `src/` 디렉토리에는 user, notice, problem처럼 기능에 맞춰서 modular design을 적용하고, 여러 기능(페이지)에서 쓰이는 component는 `src/common/component` 디렉토리에서 다루는 걸로 해요

2022-06-29 11:51 UTC, dotoleeoak commented on frontend/src/contest/pages/[contestId]/Notice.vue
> +<script setup lang="ts">
`pages` 폴더 하위에 있는 vue 파일들은 모두 파일명이 소문자가 되게 해주세요~!
예시: `pages/[id]/notice.vue`, `pages/[id]/problem.vue`
참고: https://github.com/hannoeru/vite-plugin-pages#basic-routing

2022-06-29 11:51 UTC, dotoleeoak commented on frontend/src/home/pages/index.vue
> +import MyComponent from '@/home/components/MyComponent.vue'
사소한거긴 한데, `../components/MyComponent.vue`로 상대경로 쓰는 게 나을 것 같아요.
절대 경로는 다른 module 것 import할 때 쓰는 방향으로 하고요.

2022-06-29 11:51 UTC, dotoleeoak commented on frontend/src/home/pages/index.vue
> +</style>-->
우리가 Tailwind CSS를 쓰니까 대부분의 경우는 CSS를 직접 작성할 일이 없을테니 이 부분도 지우는 게 좋을 것 같습니다!

2022-06-29 11:51 UTC, dotoleeoak commented on frontend/vite.config.ts
> +    })
https://github.com/skkuding/next/pull/39#discussion_r851020351
전에 `vite-plugin-pages` 세팅하면서 이런 이유로 이렇게 설정해두긴 했는데, 어떤 방향이 나을 것 같나요?

2022-07-01 08:57 UTC, goo314 commented on frontend/tailwind.config.js
> +        DEFUALT: '#2279fd',
여기 DEFAULT 오타 났어요 수정 부탁드려요 😘

2022-07-01 13:40 UTC, dotoleeoak commented on frontend/vite.config.ts
> +    })
예를 들어서 group 폴더 내에서 정의하는 페이지더라도 라우팅이 `/group/:id` 꼴일 수도 있고, `/user/:id/group/:id` 꼴일 수도 있는 것처럼요(예시로만 만들어본 route입니다). 이 경우 후자를 group 폴더 내에 만들어야 하면 지금 설정처럼 `baseRoute`를 지정해두면 만들기 어렵고, `baseRoute`를 root(`/`)로 지정하면 `group/pages/user/...` 디렉토리에 파일을 만들면 되겠죠?

2022-07-01 13:44 UTC, dotoleeoak commented on frontend/vite.config.ts
> +    })
근데 사실 지금처럼 `baseRoute`를 지정해둔 세팅도 위처럼 다른 base로 시작하는 route를 만드는 게 불가능하진 않아요. [custom block](https://github.com/hannoeru/vite-plugin-pages#sfc-custom-block-for-route-data)을 쓰면 가능해서, 이게 더 직관적이고 깔끔해보이면 지금 세팅으로 둬도 상관은 없어 보여요. 그냥 취향 차이인 것 같습니당

2022-07-01 14:39 UTC, dotoleeoak commented on frontend/src/App.vue
> +  <div class="text-text px-page_s md:px-page">
`px-page_s`랑 `md:px-page`는 header나 footer처럼 나중에 width를 100%로 해야할 때 문제가 있을 것 같은데, 이건 각 페이지에서 설정하는 거 어떤가요? 전체 페이지에 일괄적으로 적용하는게 좋아보이면 나중에 [`vite-plugin-vue-layouts`](https://github.com/JohnCampionJr/vite-plugin-vue-layouts)로 구현하는 것도 괜찮을 거 같아요

2022-07-01 23:32 UTC, dotoleeoak approved these changes

2022-07-02 01:10 UTC, merged