feat(be): use argon2
skkuding/next pull request #91
Opened 2022-06-30 14:08 UTC by Anzanda

### Description

`Argon2`모듈로 중요한 정보들을 해쉬화하여 저장하도록 합니다. 따로 `auth/common`경로에 `Hash`클래스를 구현하였습니다. `Argon2`와의 의존성을 최소화하기 위함입니다.

### Additional context

`validatePassword()`함수에서 인자의 순서가 강제됩니다. "해쉬화된 비번", "플레인 비번" 순서입니다. 개인적으로 이게 불편하긴한데 방법이 떠오르질 않네요.

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [ ] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-06-30 16:13 UTC, cranemont requested changes

2022-06-30 16:13 UTC, cranemont commented on backend/src/auth/common/hash.ts
> +export class Hash {
class를 쓴 이유가 있을까요? function으로도 충분하지 않을까 해서요 🤔

2022-06-30 16:13 UTC, cranemont commented on backend/src/auth/common/hash.ts
> +  async decryptPassword(password: string): Promise<string> {
encrypt가 더 적합할 것 같습니당

2022-07-01 03:24 UTC, Anzanda commented on backend/src/auth/common/hash.ts
> +export class Hash {
인정함니다 그럼 `export default`로? 하나요

2022-07-01 03:25 UTC, Anzanda commented on backend/src/auth/common/hash.ts
> +  async decryptPassword(password: string): Promise<string> {
앗 맞네요 수정할게요

2022-07-01 03:47 UTC, Anzanda commented
> 이건 사소한 걸수도 있는데 password가 들어간 specific한 변수/함수명 말고 그냥 general하게 쓰는건 어떨까요? 예를 들면 `encrypt(text)`처럼요. 나중에 hashing이 필요한 다른 곳에서도 쓰일 가능성이 있다는 생각이 드네요

이건 저도 작성하면서 고민했던 부분인데, 이게 맞는 거 같아요. 애초에 중요한 "정보"들을 해쉬화하려고 도입한거니까

2022-07-01 10:39 UTC, cranemont approved these changes
@Anzanda 좋습니당

2022-07-01 11:22 UTC, SH9480P approved these changes
확인했습니다~

2022-07-03 05:16 UTC, merged