feat(fe): add card-item component
skkuding/next pull request #94
Opened 2022-07-02 05:42 UTC by goo314

### Description

- 반응형 CardItem 구현
close #69 

화면 크기 > 768px 일때
<img width="900" alt="image" src="https://user-images.githubusercontent.com/62930375/176987860-cf9fd734-51aa-4cc0-8cd6-97763f0553a5.png">

화면크기 <= 768 일때
<img width="400" alt="image" src="https://user-images.githubusercontent.com/62930375/176987869-5e2a3e0c-0bc3-4068-b0f0-3fc7ac447aa5.png">

### Additional context

- props 속성
  - ccolor (string) : border 색상 (green, gray)
  - img (string) : image 경로
  - leftTop (string) : 왼쪽위에 위치할 글 -- bold 글씨
  - rightTop (string) : 오른쪽 위에 위치할 글
  - leftBottom (string) : 왼쪽 아래에 위치할 글 -- 회색 글씨
  - rightBottomFull (string) : 화면크기 768초과 일때 오른쪽 아래에 위치할 글 -- 초록 글씨
  - rightBottomShort (string) : 화면크기 768이하일때 오른쪽 아래에 위치할 글 -- 초록 글씨
 
- 사용 예시
```
<CardItem
    ccolor="gray"
    img="/favicon.ico"
    tag-type="administrator"
    left-top="SKKUDING"
    right-top="Member: 23"
    left-bottom="SKKU 코딩 플랫폼 개발 동아리입니다."
    right-bottom-full="Created by 하설빙"
    right-bottom-short="By 하설빙"
  />
```

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [x] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#pr-and-branch) and follow the [Commit Convention](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md#commit-convention)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2022-07-02 10:07 UTC, dotoleeoak requested changes

2022-07-02 10:07 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/CardItem.vue
> +        </div>
`full`과 `short`를 따로 정의하는 대신에 tailwindcss의 `truncate` class로 글씨 자체를 잘라버리는 건 어떤가요?
https://tailwindcss.com/docs/text-overflow

2022-07-02 10:07 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/CardItem.vue
> +}>()
props를 입력 안했을 때 이런 에러가 뜨는데, typescript에서는 `?`로 optional임을 명시해줘야 돼서 추가 부탁드릴게요!

![image](https://user-images.githubusercontent.com/19747913/176995930-4d2b7317-a400-41f2-9530-b0370236642d.png)

2022-07-02 10:07 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/CardItem.vue
> +    <img :src="img" class="aspect-square w-16" />
`img` prop이 없으면 img 태그가 깨져서 보이는데, 만약 img가 선택적이면 `v-if`를 추가하는 게 좋을 것 같습니다

2022-07-02 10:46 UTC, goo314 commented on frontend/src/common/components/Molecule/CardItem.vue
> +}>()
원래 title, subtitle, description, subdescription으로 할려고 했는데
부모 컴포넌트에서 가져다 쓸 때 개인적으로 헷갈려서 바꿨었어요🤔
additionalText는 오른쪽 위에 위치한 글 말씀하시는 거죠?

마땅한 이름이 없어서 저렇게 지정했었는데, 재민오빠가 추천해준 이름도 괜찮네요
바꾸겠습니다

2022-07-02 10:48 UTC, goo314 commented on frontend/src/common/components/Molecule/CardItem.vue
> +  ccolor: string
card-color이었어서 ccolor라고 했었는데 😀
수정하겠습니다

2022-07-02 10:51 UTC, goo314 commented on frontend/src/common/components/Molecule/CardItem.vue
> +        </div>
그걸 사실 하려고 했었는데 시간이랑 그룹생성자랑 다른 디자인이라 일부러 저렇게 넣었어요
시간은 큰 화면에서 Start After (time) 작은 화면에서는 +(time) 혹은 -(time)
그룹생성자는 큰 화면에서 Created by (creator), 작은 화면에서는 by(creator)
이렇게 해야 작은 화면에서도 중요한 정보만 보일 것 같아서요! 😃
어떤게 좋으실까요?

2022-07-02 11:00 UTC, goo314 commented on frontend/src/common/components/Molecule/CardItem.vue
> +}>()
title은 중요해서 뺴고 나머지는 optional 명시해주겠습니다!

2022-07-02 11:01 UTC, goo314 commented on frontend/src/common/components/Molecule/CardItem.vue
> +    <img :src="img" class="aspect-square w-16" />
넹~

2022-07-02 11:28 UTC, goo314 commented on frontend/src/common/components/Molecule/CardItem.vue
> +const borderColor: borderColorType = {
명시해주지 않으면 borderColor[ccolor]에서 오류가 떠서 함수로 바꿨습니다!

2022-07-02 13:47 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/CardItem.vue
>  }
음 이것보단 type을 정의해서 이렇게 해보는 거 어떨까요?

1. 일단 `borderColor`의 type을 정의해서 받을 수 있는 prop을 제한하고,
```ts
type BorderColor = 'gray' | 'green'

const props = defineProps<{
  borderColor?: BorderColor
  ...
}>()
```

2. class로 넘겨주는 건 method(function) 대신에 computed가 맥락상 좀 더 적합해보여요
```ts
const borderColorClass = computed(() => {
  return props.borderColor === 'gray' ? 'border-gray' : 'border-green'
})
```
```html
<div :class="borderColorClass">...</div>
```

2022-07-02 13:47 UTC, dotoleeoak commented on frontend/src/common/components/Molecule/CardItem.vue
> +        </div>
그러면 이대로 둬도 괜찮을 것 같네요
하나만 추가하면 `coloredTextShort`를 따로 적을 필요가 없을 때에는 `coloredText`랑 `coloredTextShort`에 똑같은 걸 두 번 적어야되니까 대신에 `{{ coloredTextShort || coloredText }}`로 바꾸는 거 어떤가요?

2022-07-02 14:02 UTC, goo314 commented on frontend/src/common/components/Molecule/CardItem.vue
> +        </div>
좋아요!

2022-07-02 14:03 UTC, goo314 commented on frontend/src/common/components/Molecule/CardItem.vue
>  }
친절한 코멘트...! 감사합니다 😆

2022-07-02 14:23 UTC, dotoleeoak approved these changes
좋습니다~

2022-07-03 09:07 UTC, SOLBI1028 commented on frontend/src/common/components/Molecule/CardItem.vue
> +    class="mx-40 flex cursor-pointer border p-3 hover:shadow"
`mx-40`은 컴포넌트 테스트용으로 추가해둔 것 같은데 빼도 될것 같아요~!

2022-07-03 09:07 UTC, SOLBI1028 commented on frontend/src/common/components/Molecule/CardItem.vue
> +          class="text-green absolute bottom-0 right-0 block text-right md:hidden"
border가 gray일 때는 해당 text 부분도 gray가 되어야 할 것 같아요~!

2022-07-03 09:08 UTC, goo314 commented on frontend/src/common/components/Molecule/CardItem.vue
> +    class="mx-40 flex cursor-pointer border p-3 hover:shadow"
아 맞다!!!!!!!!!!!!!!!! 깜빡했어요 수정할게요😆

2022-07-03 09:12 UTC, goo314 commented on frontend/src/common/components/Molecule/CardItem.vue
> +          class="text-green absolute bottom-0 right-0 block text-right md:hidden"
네~~~~~~~ 바로 고칠게요😉

2022-07-03 10:28 UTC, SOLBI1028 approved these changes

2022-07-03 10:38 UTC, merged